use serde::Serialize;

#[derive(Debug, Serialize)]
pub(in crate::commands::real_full) struct RealFullExpertResidualChainNvfp4Probe {
    pub(in crate::commands::real_full) status: &'static str,
    pub(in crate::commands::real_full) scope: &'static str,
    pub(in crate::commands::real_full) opt_in_env: &'static str,
    pub(in crate::commands::real_full) hidden_source: &'static str,
    pub(in crate::commands::real_full) quant_recipe: &'static str,
    pub(in crate::commands::real_full) sparse_layers: usize,
    pub(in crate::commands::real_full) layers_executed: usize,
    pub(in crate::commands::real_full) top_k_per_layer: usize,
    pub(in crate::commands::real_full) routes_executed: usize,
    pub(in crate::commands::real_full) intermediate_rows: usize,
    pub(in crate::commands::real_full) output_rows: usize,
    pub(in crate::commands::real_full) residual_prefix_values: usize,
    pub(in crate::commands::real_full) residual_adds: usize,
    pub(in crate::commands::real_full) router_weight_bytes_read: u64,
    pub(in crate::commands::real_full) router_bias_bytes_read: u64,
    pub(in crate::commands::real_full) weight_tensors_read: usize,
    pub(in crate::commands::real_full) quant_metadata_tensors_read: usize,
    pub(in crate::commands::real_full) weight_bytes_read: u64,
    pub(in crate::commands::real_full) quant_metadata_bytes_read: u64,
    pub(in crate::commands::real_full) output_checksum: Option<f64>,
    pub(in crate::commands::real_full) output_l2_norm: Option<f32>,
    pub(in crate::commands::real_full) initial_residual_checksum: Option<f64>,
    pub(in crate::commands::real_full) residual_delta_checksum: Option<f64>,
    pub(in crate::commands::real_full) final_residual_checksum: Option<f64>,
    pub(in crate::commands::real_full) first_residual_before: Option<f32>,
    pub(in crate::commands::real_full) first_residual_after: Option<f32>,
    pub(in crate::commands::real_full) last_residual_before: Option<f32>,
    pub(in crate::commands::real_full) last_residual_after: Option<f32>,
    pub(in crate::commands::real_full) first_layer_id: Option<usize>,
    pub(in crate::commands::real_full) last_layer_id: Option<usize>,
    pub(in crate::commands::real_full) first_expert_id: Option<usize>,
    pub(in crate::commands::real_full) last_expert_id: Option<usize>,
    pub(in crate::commands::real_full) layer_summaries:
        Vec<RealFullExpertResidualChainNvfp4LayerProbe>,
    pub(in crate::commands::real_full) uses_real_nvfp4_weights: bool,
    pub(in crate::commands::real_full) uses_real_router: bool,
    pub(in crate::commands::real_full) applies_sparse_mlp_residual_chain: bool,
    pub(in crate::commands::real_full) includes_attention: bool,
    pub(in crate::commands::real_full) includes_dense_layers: bool,
    pub(in crate::commands::real_full) includes_shared_expert: bool,
    pub(in crate::commands::real_full) covers_all_sparse_layers: bool,
    pub(in crate::commands::real_full) covers_full_top_k: bool,
    pub(in crate::commands::real_full) uses_full_model_residual: bool,
    pub(in crate::commands::real_full) passed: bool,
    pub(in crate::commands::real_full) skipped_reason: Option<String>,
}

#[derive(Debug, Serialize)]
pub(in crate::commands::real_full) struct RealFullExpertResidualChainNvfp4LayerProbe {
    pub(in crate::commands::real_full) layer_id: usize,
    pub(in crate::commands::real_full) expert_id: usize,
    pub(in crate::commands::real_full) owner: String,
    pub(in crate::commands::real_full) score: f32,
    pub(in crate::commands::real_full) corrected_score: f32,
    pub(in crate::commands::real_full) output_checksum: f64,
    pub(in crate::commands::real_full) output_l2_norm: f32,
    pub(in crate::commands::real_full) residual_before_checksum: f64,
    pub(in crate::commands::real_full) residual_delta_checksum: f64,
    pub(in crate::commands::real_full) residual_after_checksum: f64,
    pub(in crate::commands::real_full) first_residual_after: f32,
    pub(in crate::commands::real_full) last_residual_after: f32,
}

#[derive(Debug, Serialize)]
pub(in crate::commands::real_full) struct RealFullExpertSparseMlpSharedChainProbe {
    pub(in crate::commands::real_full) status: &'static str,
    pub(in crate::commands::real_full) scope: &'static str,
    pub(in crate::commands::real_full) opt_in_env: &'static str,
    pub(in crate::commands::real_full) hidden_source: &'static str,
    pub(in crate::commands::real_full) quant_recipe: &'static str,
    pub(in crate::commands::real_full) row_mode: &'static str,
    pub(in crate::commands::real_full) sparse_layers: usize,
    pub(in crate::commands::real_full) layers_executed: usize,
    pub(in crate::commands::real_full) top_k_per_layer: usize,
    pub(in crate::commands::real_full) routes_executed: usize,
    pub(in crate::commands::real_full) shared_expert_layers_executed: usize,
    pub(in crate::commands::real_full) routed_intermediate_rows: usize,
    pub(in crate::commands::real_full) shared_intermediate_rows: usize,
    pub(in crate::commands::real_full) output_rows: usize,
    pub(in crate::commands::real_full) covers_full_output_rows: bool,
    pub(in crate::commands::real_full) residual_prefix_values: usize,
    pub(in crate::commands::real_full) residual_adds: usize,
    pub(in crate::commands::real_full) router_weight_bytes_read: u64,
    pub(in crate::commands::real_full) router_bias_bytes_read: u64,
    pub(in crate::commands::real_full) routed_weight_tensors_read: usize,
    pub(in crate::commands::real_full) routed_quant_metadata_tensors_read: usize,
    pub(in crate::commands::real_full) routed_weight_bytes_read: u64,
    pub(in crate::commands::real_full) routed_quant_metadata_bytes_read: u64,
    pub(in crate::commands::real_full) shared_weight_tensors_read: usize,
    pub(in crate::commands::real_full) shared_weight_bytes_read: u64,
    pub(in crate::commands::real_full) shared_gate_proj_bytes_read: u64,
    pub(in crate::commands::real_full) shared_up_proj_bytes_read: u64,
    pub(in crate::commands::real_full) shared_down_proj_bytes_read: u64,
    pub(in crate::commands::real_full) output_checksum: Option<f64>,
    pub(in crate::commands::real_full) output_l2_norm: Option<f32>,
    pub(in crate::commands::real_full) initial_residual_checksum: Option<f64>,
    pub(in crate::commands::real_full) residual_delta_checksum: Option<f64>,
    pub(in crate::commands::real_full) final_residual_checksum: Option<f64>,
    pub(in crate::commands::real_full) first_residual_before: Option<f32>,
    pub(in crate::commands::real_full) first_residual_after: Option<f32>,
    pub(in crate::commands::real_full) last_residual_before: Option<f32>,
    pub(in crate::commands::real_full) last_residual_after: Option<f32>,
    pub(in crate::commands::real_full) first_layer_id: Option<usize>,
    pub(in crate::commands::real_full) last_layer_id: Option<usize>,
    pub(in crate::commands::real_full) first_expert_id: Option<usize>,
    pub(in crate::commands::real_full) last_expert_id: Option<usize>,
    pub(in crate::commands::real_full) layer_summaries:
        Vec<RealFullExpertSparseMlpSharedChainLayerProbe>,
    pub(in crate::commands::real_full) uses_real_nvfp4_weights: bool,
    pub(in crate::commands::real_full) uses_real_router: bool,
    pub(in crate::commands::real_full) uses_real_shared_expert_weights: bool,
    pub(in crate::commands::real_full) applies_sparse_mlp_residual_chain: bool,
    pub(in crate::commands::real_full) includes_attention: bool,
    pub(in crate::commands::real_full) includes_dense_layers: bool,
    pub(in crate::commands::real_full) includes_shared_expert: bool,
    pub(in crate::commands::real_full) covers_all_sparse_layers: bool,
    pub(in crate::commands::real_full) covers_full_top_k: bool,
    pub(in crate::commands::real_full) uses_full_model_residual: bool,
    pub(in crate::commands::real_full) passed: bool,
    pub(in crate::commands::real_full) skipped_reason: Option<String>,
}

#[derive(Debug, Serialize)]
pub(in crate::commands::real_full) struct RealFullExpertSparseMlpSharedChainLayerProbe {
    pub(in crate::commands::real_full) layer_id: usize,
    pub(in crate::commands::real_full) expert_id: usize,
    pub(in crate::commands::real_full) owner: String,
    pub(in crate::commands::real_full) score: f32,
    pub(in crate::commands::real_full) corrected_score: f32,
    pub(in crate::commands::real_full) routed_output_checksum: f64,
    pub(in crate::commands::real_full) shared_output_checksum: f64,
    pub(in crate::commands::real_full) output_checksum: f64,
    pub(in crate::commands::real_full) output_l2_norm: f32,
    pub(in crate::commands::real_full) residual_before_checksum: f64,
    pub(in crate::commands::real_full) residual_delta_checksum: f64,
    pub(in crate::commands::real_full) residual_after_checksum: f64,
    pub(in crate::commands::real_full) expert_input_norm_backend: &'static str,
    pub(in crate::commands::real_full) router_backend: &'static str,
    pub(in crate::commands::real_full) shared_mlp_backend: &'static str,
    pub(in crate::commands::real_full) residual_add_backend: &'static str,
    pub(in crate::commands::real_full) first_residual_after: f32,
    pub(in crate::commands::real_full) last_residual_after: f32,
}
