use glmrt_core::{GLM52_FIRST_K_DENSE_REPLACE, GLM52_HIDDEN_SIZE, GLM52_NUM_HIDDEN_LAYERS};

use super::super::super::constants::{
    REAL_FULL_PREFLIGHT_DECODE_ROWS, REAL_FULL_PREFLIGHT_MTP_ROWS, REAL_FULL_PREFLIGHT_PREFILL_ROWS,
};
use super::super::super::types::{
    RealGlmFullPreflightReport, REAL_FULL_RESIDUAL_COMPLETION_BLOCKER,
};

pub(super) fn assert_residual_sampling_report(report: &RealGlmFullPreflightReport) {
    assert_eq!(
        report.residual_stream_dry_run.layer_count,
        GLM52_NUM_HIDDEN_LAYERS
    );
    assert_eq!(
        report.residual_stream_dry_run.row_count,
        REAL_FULL_PREFLIGHT_PREFILL_ROWS
            + REAL_FULL_PREFLIGHT_MTP_ROWS
            + REAL_FULL_PREFLIGHT_DECODE_ROWS
    );
    assert_eq!(
        report.residual_stream_dry_run.total_residual_adds,
        GLM52_NUM_HIDDEN_LAYERS * 2
    );
    assert_eq!(
        report.residual_stream_dry_run.dense_layers,
        GLM52_FIRST_K_DENSE_REPLACE
    );
    assert_eq!(
        report.residual_stream_dry_run.sparse_layers,
        GLM52_NUM_HIDDEN_LAYERS - GLM52_FIRST_K_DENSE_REPLACE
    );
    assert_eq!(
        report.residual_stream_dry_run.terminal_stages,
        ["final_norm", "lm_head", "full_vocab_sampling"]
    );
    assert!(report.residual_stream_dry_run.layer_order_verified);
    assert!(
        report
            .residual_stream_dry_run
            .numeric_kernel_self_test
            .passed
    );
    assert_eq!(
        report
            .residual_stream_dry_run
            .numeric_kernel_self_test
            .layers,
        3
    );
    assert_eq!(
        report
            .residual_stream_dry_run
            .numeric_kernel_self_test
            .residual_adds,
        6
    );
    assert_eq!(
        report
            .residual_stream_dry_run
            .numeric_kernel_self_test
            .values_updated,
        48
    );
    assert!(
        (report
            .residual_stream_dry_run
            .numeric_kernel_self_test
            .final_checksum
            - 12.0)
            .abs()
            < 1.0e-6
    );
    assert_eq!(
        report
            .residual_stream_dry_run
            .real_attention_residual_prefix_probe
            .status,
        "error"
    );
    assert_eq!(
        report
            .residual_stream_dry_run
            .real_attention_residual_prefix_probe
            .layer_id,
        0
    );
    assert_eq!(
        report
            .residual_stream_dry_run
            .real_attention_residual_prefix_probe
            .output_prefix_values,
        4
    );
    assert!(
        !report
            .residual_stream_dry_run
            .real_attention_residual_prefix_probe
            .passed
    );
    assert!(report
        .residual_stream_dry_run
        .real_attention_residual_prefix_probe
        .skipped_reason
        .is_some());
    assert!(
        !report
            .residual_stream_dry_run
            .real_attention_residual_prefix_probe
            .applies_attention_residual_prefix
    );
    assert!(
        !report
            .residual_stream_dry_run
            .real_attention_residual_prefix_probe
            .includes_mla_softmax
    );
    assert_eq!(
        report
            .residual_stream_dry_run
            .real_mla_rope_attention_probe
            .status,
        "error"
    );
    assert_eq!(
        report
            .residual_stream_dry_run
            .real_mla_rope_attention_probe
            .attention_heads,
        2
    );
    assert_eq!(
        report
            .residual_stream_dry_run
            .real_mla_rope_attention_probe
            .qk_rope_head_dim,
        64
    );
    assert!(
        !report
            .residual_stream_dry_run
            .real_mla_rope_attention_probe
            .passed
    );
    assert!(report
        .residual_stream_dry_run
        .real_mla_rope_attention_probe
        .skipped_reason
        .is_some());
    assert!(
        !report
            .residual_stream_dry_run
            .real_mla_rope_attention_probe
            .includes_mla_softmax
    );
    assert_eq!(
        report
            .residual_stream_dry_run
            .real_dsa_indexer_attention_probe
            .status,
        "error"
    );
    assert_eq!(
        report
            .residual_stream_dry_run
            .real_dsa_indexer_attention_probe
            .layer_id,
        22
    );
    assert_eq!(
        report
            .residual_stream_dry_run
            .real_dsa_indexer_attention_probe
            .dsa_query_dim,
        128
    );
    assert!(
        !report
            .residual_stream_dry_run
            .real_dsa_indexer_attention_probe
            .passed
    );
    assert!(report
        .residual_stream_dry_run
        .real_dsa_indexer_attention_probe
        .skipped_reason
        .is_some());
    assert!(
        !report
            .residual_stream_dry_run
            .real_dsa_indexer_attention_probe
            .includes_dsa_softmax
    );
    assert_eq!(
        report
            .residual_stream_dry_run
            .real_dense_prefix_probe
            .status,
        "error"
    );
    assert_eq!(
        report
            .residual_stream_dry_run
            .real_dense_prefix_probe
            .opt_in_env,
        "GLMRT_REAL_FULL_PROBE_DENSE_PREFIX"
    );
    assert_eq!(
        report
            .residual_stream_dry_run
            .real_dense_prefix_probe
            .layers_executed,
        0
    );
    assert!(report
        .residual_stream_dry_run
        .real_dense_prefix_probe
        .skipped_reason
        .is_some());
    assert!(
        !report
            .residual_stream_dry_run
            .real_dense_prefix_probe
            .covers_all_dense_layers
    );
    assert_eq!(
        report
            .residual_stream_dry_run
            .real_attention_dense_sparse_prefix_probe
            .status,
        "not-run"
    );
    assert!(
        !report
            .residual_stream_dry_run
            .real_attention_dense_sparse_prefix_probe
            .passed
    );
    assert!(report
        .residual_stream_dry_run
        .real_attention_dense_sparse_prefix_probe
        .skipped_reason
        .is_some());
    assert!(
        !report
            .residual_stream_dry_run
            .real_attention_dense_sparse_prefix_probe
            .includes_attention
    );
    assert!(
        !report
            .residual_stream_dry_run
            .real_attention_dense_sparse_prefix_probe
            .covers_all_sparse_layers
    );
    assert!(
        !report
            .residual_stream_dry_run
            .real_attention_dense_sparse_prefix_probe
            .uses_full_model_residual
    );
    assert_eq!(
        report
            .residual_stream_dry_run
            .real_layer_ordered_prefix_probe
            .status,
        "error"
    );
    assert_eq!(
        report
            .residual_stream_dry_run
            .real_layer_ordered_prefix_probe
            .layer_id,
        0
    );
    assert!(
        !report
            .residual_stream_dry_run
            .real_layer_ordered_prefix_probe
            .passed
    );
    assert!(report
        .residual_stream_dry_run
        .real_layer_ordered_prefix_probe
        .skipped_reason
        .is_some());
    assert!(
        !report
            .residual_stream_dry_run
            .real_layer_ordered_prefix_probe
            .carries_attention_residual_into_mlp
    );
    assert_eq!(
        report
            .residual_stream_dry_run
            .real_layer_ordered_execution_probe
            .status,
        "error"
    );
    assert_eq!(
        report
            .residual_stream_dry_run
            .real_layer_ordered_execution_probe
            .attention_steps_missing,
        GLM52_NUM_HIDDEN_LAYERS
    );
    assert!(
        !report
            .residual_stream_dry_run
            .real_layer_ordered_execution_probe
            .passed
    );
    assert!(
        !report
            .residual_stream_dry_run
            .real_layer_ordered_execution_probe
            .full_residual_stream_complete
    );
    assert_eq!(
        report
            .residual_stream_dry_run
            .real_layer_ordered_execution_probe
            .full_residual_stream_blocker,
        Some(REAL_FULL_RESIDUAL_COMPLETION_BLOCKER)
    );
    assert!(
        !report
            .residual_stream_dry_run
            .real_layer_ordered_execution_probe
            .completion_gates
            .ready_for_full_residual_stream
    );
    assert_eq!(
        report
            .residual_stream_dry_run
            .real_layer_ordered_execution_probe
            .completion_gates
            .missing_gate_count,
        12
    );
    assert!(
        !report
            .residual_stream_dry_run
            .real_layer_ordered_execution_probe
            .execution_stepper
            .completion_gates
            .uses_cuda_coordinator_kernels
    );
    assert!(
        !report
            .residual_stream_dry_run
            .real_layer_ordered_execution_probe
            .execution_stepper
            .completion_gates
            .uses_graph_captured_coordinator_kernels
    );
    assert!(
        !report
            .residual_stream_dry_run
            .real_layer_ordered_execution_probe
            .execution_stepper
            .completion_gates
            .uses_embedding_residual_input
    );
    assert!(
        !report
            .residual_stream_dry_run
            .real_layer_ordered_execution_probe
            .execution_stepper
            .completion_gates
            .uses_full_context_mla_dsa_attention
    );
    assert_eq!(
        report
            .residual_stream_dry_run
            .real_layer_ordered_execution_probe
            .execution_stepper
            .full_residual_stream_blocker,
        Some(REAL_FULL_RESIDUAL_COMPLETION_BLOCKER)
    );
    assert!(report
        .residual_stream_dry_run
        .real_layer_ordered_execution_probe
        .skipped_reason
        .is_some());
    assert_eq!(
        report.residual_stream_dry_run.layer_dry_runs[0].layer_kind,
        "dense-mlp"
    );
    assert!(!report.residual_stream_dry_run.layer_dry_runs[0].routed_expert_exchange);
    assert!(report.residual_stream_dry_run.layer_dry_runs[3].routed_expert_exchange);
    assert_eq!(report.sampling_dry_run.lm_head_tensor, "lm_head.weight");
    assert_eq!(report.sampling_dry_run.vocab_size, 154_880);
    assert_eq!(report.sampling_dry_run.hidden_dim, GLM52_HIDDEN_SIZE);
    assert_eq!(
        report.sampling_dry_run.sampled_rows,
        REAL_FULL_PREFLIGHT_DECODE_ROWS
    );
    assert_eq!(report.sampling_dry_run.chunk_rows, 1_024);
    assert_eq!(report.sampling_dry_run.chunk_count, 152);
    assert_eq!(report.sampling_dry_run.final_chunk_rows, 256);
    assert_eq!(report.sampling_dry_run.lm_head_bytes, 1_903_165_440);
    assert_eq!(
        report.sampling_dry_run.logical_lm_head_read_bytes,
        1_903_165_440
    );
    assert_eq!(report.sampling_dry_run.dot_products, 154_880);
    assert_eq!(report.sampling_dry_run.multiply_accumulate_ops, 951_582_720);
    assert_eq!(
        report
            .sampling_dry_run
            .real_lm_head_default_chunk_probe
            .status,
        "error"
    );
    assert_eq!(
        report
            .sampling_dry_run
            .real_lm_head_default_chunk_probe
            .hidden_dim,
        GLM52_HIDDEN_SIZE
    );
    assert_eq!(
        report
            .sampling_dry_run
            .real_lm_head_default_chunk_probe
            .vocab_size,
        154_880
    );
    assert_eq!(
        report
            .sampling_dry_run
            .real_lm_head_default_chunk_probe
            .chunk_rows,
        1_024
    );
    assert!(
        !report
            .sampling_dry_run
            .real_lm_head_default_chunk_probe
            .passed
    );
    assert!(report
        .sampling_dry_run
        .real_lm_head_default_chunk_probe
        .error
        .is_some());
    assert_eq!(
        report.sampling_dry_run.real_lm_head_full_vocab_probe.status,
        "not-run"
    );
    assert!(!report.sampling_dry_run.real_lm_head_full_vocab_probe.passed);
    assert!(
        !report
            .sampling_dry_run
            .real_lm_head_full_vocab_probe
            .uses_full_model_residual
    );
    assert!(
        !report
            .sampling_dry_run
            .real_lm_head_full_vocab_probe
            .uses_real_attention_prefix
    );
    assert!(
        !report
            .sampling_dry_run
            .real_lm_head_full_vocab_probe
            .uses_real_nvfp4_residual_prefix
    );
    assert!(
        !report
            .sampling_dry_run
            .real_lm_head_full_vocab_probe
            .uses_real_sparse_mlp_shared_chain
    );
    assert_eq!(
        report
            .sampling_dry_run
            .real_lm_head_full_vocab_probe
            .residual_prefix_values,
        0
    );
    assert_eq!(
        report
            .sampling_dry_run
            .real_lm_head_full_vocab_probe
            .residual_after_checksum,
        None
    );
    assert_eq!(
        report
            .sampling_dry_run
            .real_lm_head_full_vocab_probe
            .opt_in_env,
        "GLMRT_REAL_FULL_SCORE_LM_HEAD"
    );
    assert!(report.sampling_dry_run.covers_full_vocabulary);
    assert!(report.sampling_dry_run.requires_numeric_logits);
}
