// @generated by python/tools/calibrate_dspark_cost_profile.py; do not edit.
pub(super) const GLM52_REDHAT_DSPARK_COST_PROFILE_ID: &str =
    "glm52-luke49cd-redhat8bc9-1rtx4spark-w4a16-tp4-400w-route-v2";
pub(super) const GLM52_REDHAT_DSPARK_COST_PROFILE_SOURCE_SHA256: &str =
    "0e93bed7630ec4b94c3625792b66680823c058cb7a6ecdaa89bd9f62e3f6dce1";
pub(super) const GLM52_REDHAT_DSPARK_COST_PROFILE_TARGET_MODEL: &str = "lukealonso/GLM-5.2-NVFP4";
pub(super) const GLM52_REDHAT_DSPARK_COST_PROFILE_TARGET_REVISION: &str =
    "49cd31b758371719e0a1e0988ca08867fe303c55";
pub(super) const GLM52_REDHAT_DSPARK_COST_PROFILE_DSPARK_MODEL: &str =
    "RedHatAI/GLM-5.2-speculator.dspark";
pub(super) const GLM52_REDHAT_DSPARK_COST_PROFILE_DSPARK_REVISION: &str =
    "8bc9ac46fbf507f3ee3ad82304116a1f63e9edb4";
pub(super) const GLM52_REDHAT_DSPARK_COST_PROFILE_SPARKINFER_REVISION: &str =
    "584c52a6d4779f7771dfc3f327cf3f338e2c0b1f";
pub(super) const GLM52_REDHAT_DSPARK_COST_PROFILE_TOPOLOGY: &str =
    "1x-rtx-pro-6000-sm120+4x-gb10-sm121-tp4-w4a16-fp8-rdma";
pub(super) const GLM52_REDHAT_DSPARK_COST_PROFILE_POWER_LIMIT_WATTS: usize = 400;
pub(super) const GLM52_REDHAT_DSPARK_COST_PROFILE_MAX_CONCURRENCY: usize = 4;
pub(super) const GLM52_REDHAT_DSPARK_COST_PROFILE_MAX_DRAFTS: usize = 7;
pub(super) static GLM52_REDHAT_DSPARK_COST_PROFILE_MS: [&[(usize, f64)];
    GLM52_REDHAT_DSPARK_COST_PROFILE_MAX_CONCURRENCY] = [
    &[
        (1, 48.4669), // route-standardized-corpus-mean
        (2, 71.3137), // route-standardized-corpus-mean
        (3, 90.7688), // route-standardized-corpus-mean
        (4, 99.9218), // route-standardized-corpus-mean
        (5, 113.126), // route-standardized-corpus-mean
        (6, 120.525), // route-standardized-corpus-mean
        (7, 131.6),   // route-standardized-corpus-mean
        (8, 137.38),  // route-standardized-corpus-mean
    ],
    &[
        (2, 70.0391),  // route-standardized-corpus-mean
        (3, 85.6534),  // route-standardized-corpus-mean
        (4, 96.2726),  // route-standardized-corpus-mean
        (5, 105.78),   // startup-sweep-fallback
        (6, 113.651),  // startup-sweep-fallback
        (7, 126.704),  // route-standardized-corpus-mean
        (8, 133.165),  // startup-sweep-fallback
        (9, 135.675),  // startup-sweep-fallback
        (10, 143.934), // startup-sweep-fallback
        (11, 144.042), // startup-sweep-fallback
        (12, 144.988), // startup-sweep-fallback
        (13, 147.039), // startup-sweep-fallback
        (14, 148.1),   // startup-sweep-fallback
        (15, 150.03),  // startup-sweep-fallback
        (16, 169.425), // route-standardized-corpus-mean
    ],
    &[
        (3, 103.366),  // performance-gated-baseline
        (4, 118.699),  // performance-gated-baseline
        (5, 130.176),  // performance-gated-baseline
        (6, 143.171),  // performance-gated-baseline
        (7, 153.038),  // performance-gated-baseline
        (8, 162.843),  // performance-gated-baseline
        (9, 171.286),  // performance-gated-baseline
        (10, 165.163), // performance-gated-baseline
        (11, 175.191), // performance-gated-baseline
        (12, 176.301), // performance-gated-baseline
        (13, 179.692), // performance-gated-baseline
        (14, 182.215), // performance-gated-baseline
        (15, 184.583), // performance-gated-baseline
        (16, 186.328), // performance-gated-baseline
        (17, 187.708), // performance-gated-baseline
        (18, 188.413), // performance-gated-baseline
        (19, 210.01),  // performance-gated-baseline
        (20, 194.361), // performance-gated-baseline
        (21, 196.596), // performance-gated-baseline
        (22, 200.201), // performance-gated-baseline
        (23, 203.28),  // performance-gated-baseline
        (24, 205.938), // performance-gated-baseline
    ],
    &[
        (4, 132.733),  // performance-gated-baseline
        (5, 147.506),  // performance-gated-baseline
        (6, 160.697),  // performance-gated-baseline
        (7, 172.53),   // performance-gated-baseline
        (8, 180.872),  // performance-gated-baseline
        (9, 195.2),    // performance-gated-baseline
        (10, 197.579), // performance-gated-baseline
        (11, 202.919), // performance-gated-baseline
        (12, 224.516), // performance-gated-baseline
        (13, 227.412), // performance-gated-baseline
        (14, 229.374), // performance-gated-baseline
        (15, 231.803), // performance-gated-baseline
        (16, 237.749), // performance-gated-baseline
        (17, 238.048), // performance-gated-baseline
        (18, 248.918), // performance-gated-baseline
        (19, 243.663), // performance-gated-baseline
        (20, 246.062), // performance-gated-baseline
        (21, 249.057), // performance-gated-baseline
        (22, 250.858), // performance-gated-baseline
        (23, 253.091), // performance-gated-baseline
        (24, 254.242), // performance-gated-baseline
        (25, 258.939), // performance-gated-baseline
        (26, 262.103), // performance-gated-baseline
        (27, 265.392), // performance-gated-baseline
        (28, 267.934), // performance-gated-baseline
        (29, 271.453), // performance-gated-baseline
        (30, 269.231), // performance-gated-baseline
        (31, 272.355), // performance-gated-baseline
        (32, 269.321), // performance-gated-baseline
    ],
];
