use super::super::super::types::*;

pub(super) struct BlockedRuntimeRequirementInputs<'a> {
    pub(super) attention_kv_binding_available: bool,
    pub(super) attention_kv_binding_dry_run: &'a RealFullAttentionKvBindingDryRun,
    pub(super) dense_prefix_probe: &'a RealFullDensePrefixProbe,
    pub(super) attention_residual_prefix_probe: &'a RealFullAttentionResidualPrefixProbe,
    pub(super) mla_rope_attention_probe: &'a RealFullMlaRopeAttentionProbe,
    pub(super) dsa_indexer_attention_probe: &'a RealFullDsaIndexerAttentionProbe,
    pub(super) attention_dense_sparse_prefix_probe: &'a RealFullAttentionDenseSparsePrefixProbe,
    pub(super) scheduler_real_tensor_catalog_available: bool,
    pub(super) expert_execution_dry_run: &'a RealFullExpertExecutionDryRun,
    pub(super) expert_numeric_probe: &'a RealFullExpertRealNvfp4Probe,
    pub(super) expert_all_layer_probe: &'a RealFullExpertAllLayerNvfp4Probe,
    pub(super) expert_residual_chain_probe: &'a RealFullExpertResidualChainNvfp4Probe,
    pub(super) expert_shared_chain_probe: &'a RealFullExpertSparseMlpSharedChainProbe,
    pub(super) expert_scheduler_rows_probe: &'a RealFullExpertSchedulerRowsNvfp4Probe,
    pub(super) layer_ordered_prefix_probe: &'a RealFullLayerOrderedResidualPrefixProbe,
    pub(super) layer_ordered_execution_probe: &'a RealFullLayerOrderedResidualExecutionProbe,
    pub(super) scheduler_execution_dry_run: &'a RealFullSchedulerExecutionDryRun,
    pub(super) residual_kernel: &'a RealFullResidualKernelSelfTest,
    pub(super) sampling_dry_run: &'a RealFullSamplingDryRun,
    pub(super) sampling_real_lm_head_probe: &'a RealFullSamplingRealLmHeadProbe,
}

pub(super) fn blocked_runtime_requirements(
    inputs: BlockedRuntimeRequirementInputs<'_>,
) -> Vec<RealFullRequirement> {
    let BlockedRuntimeRequirementInputs {
        attention_kv_binding_available,
        attention_kv_binding_dry_run,
        dense_prefix_probe,
        attention_residual_prefix_probe,
        mla_rope_attention_probe,
        dsa_indexer_attention_probe,
        attention_dense_sparse_prefix_probe,
        scheduler_real_tensor_catalog_available,
        expert_execution_dry_run,
        expert_numeric_probe,
        expert_all_layer_probe,
        expert_residual_chain_probe,
        expert_shared_chain_probe,
        expert_scheduler_rows_probe,
        layer_ordered_prefix_probe,
        layer_ordered_execution_probe,
        scheduler_execution_dry_run,
        residual_kernel,
        sampling_dry_run,
        sampling_real_lm_head_probe,
    } = inputs;

    vec![
        RealFullRequirement {
            name: "full_residual_stream_execution",
            passed: false,
            evidence: format!(
                "typed 78-layer residual-stream dry-run and numeric residual accumulator self-test pass; attention-prefix probe status={} passed={} layer={} residual_adds={} prefix_values={} projection_bytes={} o_proj_bytes={} final_checksum={:?} uses_real_attention={} includes_mla_softmax={} uses_full_model_residual={}; bounded MLA/RoPE probe status={} passed={} heads={} scores={} context_values={} output_prefix_values={} includes_rope={} includes_mla_softmax={} uses_full_model_residual={} output_checksum={:?}; bounded DSA/indexer probe status={} passed={} layer={} candidate_rows={} top_k={} selected={:?} scores={} context_values={} projection_backend={} rope_backend={} includes_rope={} includes_candidate_selection={} includes_dsa_softmax={} uses_full_model_residual={} context_checksum={:?}; dense-prefix probe status={} passed={} row_mode={} layers={} residual_adds={} output_rows={} residual_prefix_values={} covers_full_output_rows={} weight_bytes={} final_checksum={:?} covers_all_dense_layers={} includes_attention={} uses_full_model_residual={}; layer-ordered prefix probe status={} passed={} layer={} total_adds={} carries_attention_residual_into_mlp={} includes_attention={} includes_dense_mlp={} includes_sparse_mlp={} dense_checksum={:?} uses_full_model_residual={}; layer-ordered bounded execution trace status={} passed={} traced_layers={} trace_steps={} numeric_adds={}/{} missing_attention_steps={} missing_residual_adds={} dense_steps={} sparse_steps={} carries_attention_into_dense={} carries_dense_into_sparse={} input_token_id={:?} embedding_bytes_read={} embedding_checksum={:?} embedding_backend={:?} covers_full_output_rows={} full_residual_stream_complete={} uses_full_model_residual={} final_checksum={:?}; layer-ordered scheduler rows status={} passed={} source={} selected_layerwaves={} selected_rows={} row_sources={} prefill_rows={} kv_writes={} backed_kv_bytes={} layer_order_verified={} uses_live_scheduler_rows={}; execution stepper status={} covers_all_layers={} stage_order_verified={} trace_steps={} numeric_adds={}/{} residual_prefix_values={} stage_sources={}/{} stage_statuses={}/{} stage_status_counts(real,synthetic,provisional,blocked)={}/{}/{}/{} coordinator_backend_stages(total,cuda,cpu,unknown,all_cuda)={}/{}/{}/{}/{} coordinator_graphs(slots,captured,captures,launches,replayed)={}/{}/{}/{}/{} stages_with_numeric_checksums={} numeric_checksum_fields={} numeric_checksum_fields_per_stage={} stages_with_tensor_artifacts={} tensor_artifacts={} per_stage_tensor_artifacts(attention,dense,sparse)={}/{}/{} bounded_attention_oracle(status={},stage={},fixtures={},main={},dsa={},rope_modes={},dsa_selection={},covers_real_checkpoint={},passed={}) covers_full_output_rows={} full_residual_stream_complete={} uses_full_model_residual={} completion_gates(numeric,attention,residual,full_rows,embedding,scheduler,cuda,graph,mla_dsa,expert_daemon,lm_head,full_model,ready,missing)={}/{}/{}/{}/{}/{}/{}/{}/{}/{}/{}/{}/{}/{} missing_gate_names={:?} blocker={:?}; layer-ordered terminal lm_head sampling status={} passed={} hidden_source={} uses_real_lm_head={} full_output_residual={} full_vocab={} rows={}/{} logits={} chunks={} top_token={:?} top_logit={:?} residual_after_checksum={:?} gate_satisfied={}; composed attention+dense+sparse probe status={} passed={} row_mode={} attention_adds={} dense_adds={} sparse_adds={} total_adds={} routes={} shared_layers={} sparse_output_rows={} residual_prefix_values={} covers_full_output_rows={} final_checksum={:?} includes_attention={} includes_dense_layers={} includes_sparse_mlp={} includes_shared_expert={} covers_all_dense_layers={} covers_all_sparse_layers={} covers_full_top_k={} uses_full_model_residual={}; bounded real-router NVFP4 sparse-MLP probe applies_residual_prefix={} residual_prefix_values={} residual_after_checksum={:?}; sparse residual-chain probe status={} passed={} layers={} routes={} residual_adds={} residual_prefix_values={} delta_checksum={:?} final_checksum={:?} includes_attention={} includes_dense_layers={}; legacy sparse MLP shared-chain probe status={} passed={} row_mode={} layers={} routes={} shared_layers={} residual_adds={} residual_prefix_values={} output_rows={} covers_full_output_rows={} shared_weight_bytes={} final_checksum={:?} includes_shared_expert={} uses_full_model_residual={}; terminal lm_head residual-source probe status={} passed={} dense_layers={} sparse_layers={} routes={} total_residual_adds={} shared_layers={} covers_all_dense_layers={} covers_all_sparse_layers={} covers_full_top_k={} uses_real_dense_prefix={} uses_real_sparse_mlp_shared_chain={} uses_full_model_residual={} residual_after_checksum={:?}, but the residual stream still lacks full-model residual completion and omits full-context MLA/RoPE plus DSA/indexer attention correctness; self_test_layers={} residual_adds={}",
                attention_residual_prefix_probe.status,
                attention_residual_prefix_probe.passed,
                attention_residual_prefix_probe.layer_id,
                attention_residual_prefix_probe.residual_adds,
                attention_residual_prefix_probe.output_prefix_values,
                attention_residual_prefix_probe.projection_bytes_read,
                attention_residual_prefix_probe.o_proj_bytes_read,
                attention_residual_prefix_probe.residual_after_checksum,
                attention_residual_prefix_probe.uses_real_attention_weights,
                attention_residual_prefix_probe.includes_mla_softmax,
                attention_residual_prefix_probe.uses_full_model_residual,
                mla_rope_attention_probe.status,
                mla_rope_attention_probe.passed,
                mla_rope_attention_probe.attention_heads,
                mla_rope_attention_probe.causal_attention_scores,
                mla_rope_attention_probe.attention_context_values,
                mla_rope_attention_probe.output_prefix_values,
                mla_rope_attention_probe.includes_rope,
                mla_rope_attention_probe.includes_mla_softmax,
                mla_rope_attention_probe.uses_full_model_residual,
                mla_rope_attention_probe.attention_output_checksum,
                dsa_indexer_attention_probe.status,
                dsa_indexer_attention_probe.passed,
                dsa_indexer_attention_probe.layer_id,
                dsa_indexer_attention_probe.candidate_rows,
                dsa_indexer_attention_probe.dsa_top_k,
                dsa_indexer_attention_probe.selected_indices,
                dsa_indexer_attention_probe.causal_attention_scores,
                dsa_indexer_attention_probe.attention_context_values,
                dsa_indexer_attention_probe.projection_backend,
                dsa_indexer_attention_probe.rope_backend,
                dsa_indexer_attention_probe.includes_rope,
                dsa_indexer_attention_probe.includes_dsa_candidate_selection,
                dsa_indexer_attention_probe.includes_dsa_softmax,
                dsa_indexer_attention_probe.uses_full_model_residual,
                dsa_indexer_attention_probe.attention_context_checksum,
                dense_prefix_probe.status,
                dense_prefix_probe.passed,
                dense_prefix_probe.row_mode,
                dense_prefix_probe.layers_executed,
                dense_prefix_probe.residual_adds,
                dense_prefix_probe.output_rows,
                dense_prefix_probe.residual_prefix_values,
                dense_prefix_probe.covers_full_output_rows,
                dense_prefix_probe.weight_bytes_read,
                dense_prefix_probe.final_residual_checksum,
                dense_prefix_probe.covers_all_dense_layers,
                dense_prefix_probe.includes_attention,
                dense_prefix_probe.uses_full_model_residual,
                layer_ordered_prefix_probe.status,
                layer_ordered_prefix_probe.passed,
                layer_ordered_prefix_probe.layer_id,
                layer_ordered_prefix_probe.total_residual_adds,
                layer_ordered_prefix_probe.carries_attention_residual_into_mlp,
                layer_ordered_prefix_probe.includes_attention,
                layer_ordered_prefix_probe.includes_dense_mlp,
                layer_ordered_prefix_probe.includes_sparse_mlp,
                layer_ordered_prefix_probe.dense_residual_checksum,
                layer_ordered_prefix_probe.uses_full_model_residual,
                layer_ordered_execution_probe.status,
                layer_ordered_execution_probe.passed,
                layer_ordered_execution_probe.traced_layers,
                layer_ordered_execution_probe.trace_steps,
                layer_ordered_execution_probe.total_numeric_residual_adds,
                layer_ordered_execution_probe.planned_residual_adds,
                layer_ordered_execution_probe.attention_steps_missing,
                layer_ordered_execution_probe.residual_adds_missing,
                layer_ordered_execution_probe.dense_mlp_steps_executed,
                layer_ordered_execution_probe.sparse_mlp_steps_executed,
                layer_ordered_execution_probe.carries_attention_into_dense,
                layer_ordered_execution_probe.carries_dense_into_sparse,
                layer_ordered_execution_probe.input_token_id,
                layer_ordered_execution_probe.embedding_bytes_read,
                layer_ordered_execution_probe.embedding_residual_checksum,
                layer_ordered_execution_probe.embedding_kernel_backend,
                layer_ordered_execution_probe.covers_full_output_rows,
                layer_ordered_execution_probe.full_residual_stream_complete,
                layer_ordered_execution_probe.uses_full_model_residual,
                layer_ordered_execution_probe.final_residual_checksum,
                layer_ordered_execution_probe.scheduler_rows.status,
                layer_ordered_execution_probe.scheduler_rows.passed,
                layer_ordered_execution_probe.scheduler_rows.source_mode,
                layer_ordered_execution_probe.scheduler_rows.selected_layerwaves,
                layer_ordered_execution_probe.scheduler_rows.selected_rows,
                layer_ordered_execution_probe.scheduler_rows.row_sources,
                layer_ordered_execution_probe.scheduler_rows.selected_prefill_rows,
                layer_ordered_execution_probe.scheduler_rows.committed_kv_writes,
                layer_ordered_execution_probe.scheduler_rows.backed_kv_bytes,
                layer_ordered_execution_probe.scheduler_rows.layer_order_verified,
                layer_ordered_execution_probe
                    .scheduler_rows
                    .uses_live_scheduler_rows,
                layer_ordered_execution_probe.execution_stepper.status,
                layer_ordered_execution_probe.execution_stepper.covers_all_layers,
                layer_ordered_execution_probe.execution_stepper.stage_order_verified,
                layer_ordered_execution_probe.execution_stepper.trace_steps,
                layer_ordered_execution_probe.execution_stepper.total_numeric_residual_adds,
                layer_ordered_execution_probe.execution_stepper.planned_residual_adds,
                layer_ordered_execution_probe.execution_stepper.residual_prefix_values,
                layer_ordered_execution_probe
                    .execution_stepper
                    .stage_sources_recorded,
                layer_ordered_execution_probe.execution_stepper.trace_steps,
                layer_ordered_execution_probe
                    .execution_stepper
                    .stage_statuses_recorded,
                layer_ordered_execution_probe.execution_stepper.trace_steps,
                layer_ordered_execution_probe.execution_stepper.real_stage_count,
                layer_ordered_execution_probe
                    .execution_stepper
                    .synthetic_stage_count,
                layer_ordered_execution_probe
                    .execution_stepper
                    .provisional_stage_count,
                layer_ordered_execution_probe
                    .execution_stepper
                    .blocked_stage_count,
                layer_ordered_execution_probe
                    .execution_stepper
                    .coordinator_stage_count,
                layer_ordered_execution_probe
                    .execution_stepper
                    .coordinator_cuda_stage_count,
                layer_ordered_execution_probe
                    .execution_stepper
                    .coordinator_cpu_stage_count,
                layer_ordered_execution_probe
                    .execution_stepper
                    .coordinator_unknown_stage_count,
                layer_ordered_execution_probe
                    .execution_stepper
                    .uses_cuda_coordinator_kernels,
                layer_ordered_execution_probe
                    .execution_stepper
                    .coordinator_graph_slots,
                layer_ordered_execution_probe
                    .execution_stepper
                    .coordinator_graph_captured_graphs,
                layer_ordered_execution_probe
                    .execution_stepper
                    .coordinator_graph_captures,
                layer_ordered_execution_probe
                    .execution_stepper
                    .coordinator_graph_launches,
                layer_ordered_execution_probe
                    .execution_stepper
                    .uses_graph_captured_coordinator_kernels,
                layer_ordered_execution_probe
                    .execution_stepper
                    .stages_with_numeric_checksums,
                layer_ordered_execution_probe
                    .execution_stepper
                    .total_numeric_checksum_fields,
                layer_ordered_execution_probe
                    .execution_stepper
                    .numeric_checksum_fields_per_stage,
                layer_ordered_execution_probe
                    .execution_stepper
                    .stages_with_tensor_artifacts,
                layer_ordered_execution_probe
                    .execution_stepper
                    .total_tensor_artifacts,
                layer_ordered_execution_probe
                    .execution_stepper
                    .attention_tensor_artifacts_per_stage,
                layer_ordered_execution_probe
                    .execution_stepper
                    .dense_mlp_tensor_artifacts_per_stage,
                layer_ordered_execution_probe
                    .execution_stepper
                    .sparse_mlp_tensor_artifacts_per_stage,
                layer_ordered_execution_probe
                    .execution_stepper
                    .bounded_attention_oracle
                    .status,
                layer_ordered_execution_probe
                    .execution_stepper
                    .bounded_attention_oracle
                    .stepper_stage,
                layer_ordered_execution_probe
                    .execution_stepper
                    .bounded_attention_oracle
                    .fixture_count,
                layer_ordered_execution_probe
                    .execution_stepper
                    .bounded_attention_oracle
                    .main_mla_fixture_count,
                layer_ordered_execution_probe
                    .execution_stepper
                    .bounded_attention_oracle
                    .dsa_indexer_fixture_count,
                layer_ordered_execution_probe
                    .execution_stepper
                    .bounded_attention_oracle
                    .validates_rope_modes,
                layer_ordered_execution_probe
                    .execution_stepper
                    .bounded_attention_oracle
                    .validates_dsa_candidate_selection,
                layer_ordered_execution_probe
                    .execution_stepper
                    .bounded_attention_oracle
                    .covers_real_checkpoint,
                layer_ordered_execution_probe
                    .execution_stepper
                    .bounded_attention_oracle
                    .passed,
                layer_ordered_execution_probe.execution_stepper.covers_full_output_rows,
                layer_ordered_execution_probe
                    .execution_stepper
                    .full_residual_stream_complete,
                layer_ordered_execution_probe
                    .execution_stepper
                    .uses_full_model_residual,
                layer_ordered_execution_probe
                    .execution_stepper
                    .completion_gates
                    .numeric_layer_order_complete,
                layer_ordered_execution_probe
                    .execution_stepper
                    .completion_gates
                    .attention_steps_complete,
                layer_ordered_execution_probe
                    .execution_stepper
                    .completion_gates
                    .residual_adds_complete,
                layer_ordered_execution_probe
                    .execution_stepper
                    .completion_gates
                    .covers_full_output_rows,
                layer_ordered_execution_probe
                    .execution_stepper
                    .completion_gates
                    .uses_embedding_residual_input,
                layer_ordered_execution_probe
                    .execution_stepper
                    .completion_gates
                    .uses_live_scheduler_rows,
                layer_ordered_execution_probe
                    .execution_stepper
                    .completion_gates
                    .uses_cuda_coordinator_kernels,
                layer_ordered_execution_probe
                    .execution_stepper
                    .completion_gates
                    .uses_graph_captured_coordinator_kernels,
                layer_ordered_execution_probe
                    .execution_stepper
                    .completion_gates
                    .uses_full_context_mla_dsa_attention,
                layer_ordered_execution_probe
                    .execution_stepper
                    .completion_gates
                    .uses_live_expert_daemon_moe,
                layer_ordered_execution_probe
                    .execution_stepper
                    .completion_gates
                    .uses_real_lm_head_sampling_residual,
                layer_ordered_execution_probe
                    .execution_stepper
                    .completion_gates
                    .uses_full_model_residual,
                layer_ordered_execution_probe
                    .execution_stepper
                    .completion_gates
                    .ready_for_full_residual_stream,
                layer_ordered_execution_probe
                    .execution_stepper
                    .completion_gates
                    .missing_gate_count,
                layer_ordered_execution_probe
                    .execution_stepper
                    .completion_gates
                    .missing_gate_names,
                layer_ordered_execution_probe
                    .execution_stepper
                    .full_residual_stream_blocker,
                layer_ordered_execution_probe.terminal_lm_head_sampling.status,
                layer_ordered_execution_probe.terminal_lm_head_sampling.passed,
                layer_ordered_execution_probe
                    .terminal_lm_head_sampling
                    .hidden_source,
                layer_ordered_execution_probe
                    .terminal_lm_head_sampling
                    .uses_real_lm_head,
                layer_ordered_execution_probe
                    .terminal_lm_head_sampling
                    .uses_layer_ordered_full_output_residual,
                layer_ordered_execution_probe
                    .terminal_lm_head_sampling
                    .covers_full_vocabulary,
                layer_ordered_execution_probe
                    .terminal_lm_head_sampling
                    .rows_scored,
                layer_ordered_execution_probe
                    .terminal_lm_head_sampling
                    .vocab_size,
                layer_ordered_execution_probe
                    .terminal_lm_head_sampling
                    .logits_evaluated,
                layer_ordered_execution_probe
                    .terminal_lm_head_sampling
                    .chunks_scored,
                layer_ordered_execution_probe
                    .terminal_lm_head_sampling
                    .top_token_id,
                layer_ordered_execution_probe
                    .terminal_lm_head_sampling
                    .top_logit,
                layer_ordered_execution_probe
                    .terminal_lm_head_sampling
                    .residual_after_checksum,
                layer_ordered_execution_probe
                    .execution_stepper
                    .completion_gates
                    .uses_real_lm_head_sampling_residual,
                attention_dense_sparse_prefix_probe.status,
                attention_dense_sparse_prefix_probe.passed,
                attention_dense_sparse_prefix_probe.row_mode,
                attention_dense_sparse_prefix_probe.attention_residual_adds,
                attention_dense_sparse_prefix_probe.dense_residual_adds,
                attention_dense_sparse_prefix_probe.sparse_residual_adds,
                attention_dense_sparse_prefix_probe.total_residual_adds,
                attention_dense_sparse_prefix_probe.routed_routes,
                attention_dense_sparse_prefix_probe.shared_expert_layers,
                attention_dense_sparse_prefix_probe.sparse_output_rows,
                attention_dense_sparse_prefix_probe.residual_prefix_values,
                attention_dense_sparse_prefix_probe.covers_full_output_rows,
                attention_dense_sparse_prefix_probe.sparse_residual_checksum,
                attention_dense_sparse_prefix_probe.includes_attention,
                attention_dense_sparse_prefix_probe.includes_dense_layers,
                attention_dense_sparse_prefix_probe.includes_sparse_mlp,
                attention_dense_sparse_prefix_probe.includes_shared_expert,
                attention_dense_sparse_prefix_probe.covers_all_dense_layers,
                attention_dense_sparse_prefix_probe.covers_all_sparse_layers,
                attention_dense_sparse_prefix_probe.covers_full_top_k,
                attention_dense_sparse_prefix_probe.uses_full_model_residual,
                expert_numeric_probe.applies_mlp_residual_prefix,
                expert_numeric_probe.residual_prefix_values,
                expert_numeric_probe.residual_after_checksum,
                expert_residual_chain_probe.status,
                expert_residual_chain_probe.passed,
                expert_residual_chain_probe.layers_executed,
                expert_residual_chain_probe.routes_executed,
                expert_residual_chain_probe.residual_adds,
                expert_residual_chain_probe.residual_prefix_values,
                expert_residual_chain_probe.residual_delta_checksum,
                expert_residual_chain_probe.final_residual_checksum,
                expert_residual_chain_probe.includes_attention,
                expert_residual_chain_probe.includes_dense_layers,
                expert_shared_chain_probe.status,
                expert_shared_chain_probe.passed,
                expert_shared_chain_probe.row_mode,
                expert_shared_chain_probe.layers_executed,
                expert_shared_chain_probe.routes_executed,
                expert_shared_chain_probe.shared_expert_layers_executed,
                expert_shared_chain_probe.residual_adds,
                expert_shared_chain_probe.residual_prefix_values,
                expert_shared_chain_probe.output_rows,
                expert_shared_chain_probe.covers_full_output_rows,
                expert_shared_chain_probe.shared_weight_bytes_read,
                expert_shared_chain_probe.final_residual_checksum,
                expert_shared_chain_probe.includes_shared_expert,
                expert_shared_chain_probe.uses_full_model_residual,
                sampling_real_lm_head_probe.status,
                sampling_real_lm_head_probe.passed,
                sampling_real_lm_head_probe.residual_source_dense_layers,
                sampling_real_lm_head_probe.residual_source_sparse_layers,
                sampling_real_lm_head_probe.residual_source_route_count,
                sampling_real_lm_head_probe.residual_source_total_residual_adds,
                sampling_real_lm_head_probe.residual_source_shared_expert_layers,
                sampling_real_lm_head_probe.residual_source_covers_all_dense_layers,
                sampling_real_lm_head_probe.residual_source_covers_all_sparse_layers,
                sampling_real_lm_head_probe.residual_source_covers_full_top_k,
                sampling_real_lm_head_probe.uses_real_dense_prefix,
                sampling_real_lm_head_probe.uses_real_sparse_mlp_shared_chain,
                sampling_real_lm_head_probe.uses_full_model_residual,
                sampling_real_lm_head_probe.residual_after_checksum,
                residual_kernel.layers,
                residual_kernel.residual_adds
            ),
            blocker: Some(REAL_FULL_RESIDUAL_COMPLETION_BLOCKER),
        },
        RealFullRequirement {
            name: "real_attention_kv_backing_storage",
            passed: attention_kv_binding_available,
            evidence: format!(
                "real attention/KV binding dry-run covers {} layers, {} tensors, {} KV bytes/token, {} KV I/O layers, and {} prefix-read blocks",
                attention_kv_binding_dry_run.attention_layers,
                attention_kv_binding_dry_run.attention_tensors,
                attention_kv_binding_dry_run.kv_layer_bytes_sum,
                attention_kv_binding_dry_run.kv_io_layer_count,
                attention_kv_binding_dry_run.kv_io_prefix_read_blocks
            ),
            blocker: (!attention_kv_binding_available)
                .then_some("needs real attention kernel integration with the KV I/O interface"),
        },
        RealFullRequirement {
            name: "all_layer_real_nvfp4_expert_execution",
            passed: false,
            evidence: format!(
                "all-layer catalog/placement/ExpertBatch dry-run covers {}/{} routed experts and {} route entries; legacy single-row NVFP4 probe status={} passed={} row_mode={} top_k={} routes={} intermediate_rows={} output_rows={} covers_full_top_k={} covers_full_intermediate_rows={} covers_full_output_rows={} uses_real_router={} uses_full_model_residual={} covers_all_sparse_layers={}; all-sparse-layer top-k NVFP4 probe status={} passed={} layers={} routes={} covers_all_sparse_layers={} covers_full_top_k={} uses_full_model_residual={}; sparse residual-chain probe status={} passed={} layers={} routes={} covers_all_sparse_layers={} covers_full_top_k={} uses_full_model_residual={}; legacy sparse MLP shared-chain probe status={} passed={} row_mode={} layers={} routes={} shared_layers={} output_rows={} covers_full_output_rows={} covers_all_sparse_layers={} covers_full_top_k={} includes_shared_expert={} uses_full_model_residual={}; legacy mixed scheduler-row probe status={} passed={} row_mode={} source_rows={}/{} layers={} routes={} residual_adds={} intermediate_rows={} output_rows={} covers_full_output_rows={} covers_all_sparse_layers={} covers_full_top_k={} covers_sources={} covers_all_scheduler_rows={} uses_full_model_residual={}; numeric NVFP4 expert kernels are not run for all routed scheduler rows",
                expert_execution_dry_run.fully_covered_experts,
                expert_execution_dry_run.expected_routed_experts,
                expert_execution_dry_run.planned_route_entries,
                expert_numeric_probe.status,
                expert_numeric_probe.passed,
                expert_numeric_probe.row_mode,
                expert_numeric_probe.top_k,
                expert_numeric_probe.route_count,
                expert_numeric_probe.intermediate_rows,
                expert_numeric_probe.output_rows,
                expert_numeric_probe.covers_full_top_k,
                expert_numeric_probe.covers_full_intermediate_rows,
                expert_numeric_probe.covers_full_output_rows,
                expert_numeric_probe.uses_real_router,
                expert_numeric_probe.uses_full_model_residual,
                expert_numeric_probe.covers_all_sparse_layers,
                expert_all_layer_probe.status,
                expert_all_layer_probe.passed,
                expert_all_layer_probe.layers_executed,
                expert_all_layer_probe.routes_executed,
                expert_all_layer_probe.covers_all_sparse_layers,
                expert_all_layer_probe.covers_full_top_k,
                expert_all_layer_probe.uses_full_model_residual,
                expert_residual_chain_probe.status,
                expert_residual_chain_probe.passed,
                expert_residual_chain_probe.layers_executed,
                expert_residual_chain_probe.routes_executed,
                expert_residual_chain_probe.covers_all_sparse_layers,
                expert_residual_chain_probe.covers_full_top_k,
                expert_residual_chain_probe.uses_full_model_residual,
                expert_shared_chain_probe.status,
                expert_shared_chain_probe.passed,
                expert_shared_chain_probe.row_mode,
                expert_shared_chain_probe.layers_executed,
                expert_shared_chain_probe.routes_executed,
                expert_shared_chain_probe.shared_expert_layers_executed,
                expert_shared_chain_probe.output_rows,
                expert_shared_chain_probe.covers_full_output_rows,
                expert_shared_chain_probe.covers_all_sparse_layers,
                expert_shared_chain_probe.covers_full_top_k,
                expert_shared_chain_probe.includes_shared_expert,
                expert_shared_chain_probe.uses_full_model_residual,
                expert_scheduler_rows_probe.status,
                expert_scheduler_rows_probe.passed,
                expert_scheduler_rows_probe.row_mode,
                expert_scheduler_rows_probe.source_rows_executed,
                expert_scheduler_rows_probe.planned_compatible_batch_rows,
                expert_scheduler_rows_probe.layers_executed,
                expert_scheduler_rows_probe.routes_executed,
                expert_scheduler_rows_probe.residual_adds,
                expert_scheduler_rows_probe.intermediate_rows,
                expert_scheduler_rows_probe.output_rows,
                expert_scheduler_rows_probe.covers_full_output_rows,
                expert_scheduler_rows_probe.covers_all_sparse_layers,
                expert_scheduler_rows_probe.covers_full_top_k,
                expert_scheduler_rows_probe.covers_scheduler_source_modes,
                expert_scheduler_rows_probe.covers_all_scheduler_rows,
                expert_scheduler_rows_probe.uses_full_model_residual
            ),
            blocker: Some(
                "needs all routed rows/top-k routes dispatched through real NVFP4 expert execution",
            ),
        },
        RealFullRequirement {
            name: "scheduler_integration_for_real_full",
            passed: false,
            evidence: format!(
                "admitted full-model scheduler execution dry-run exists and the blocked API path now admits prefill/decode/MTP request waves; scheduler_real_tensor_catalog_available={}; scheduler sparse host batches sets={} batches={} rows={} routes={} expert_tiles={} routes_match_global={} graph_counts_valid={} request_frames={} request_rows={} request_routes={} request_payload_bytes={} request_wire_bytes={} response_frames={} response_rows={} response_payload_bytes={} response_wire_bytes={} wire_envelopes_valid={}; scheduler device KV status={} writes={} reads={} bytes={} projected_writes={} projected_bytes={} synthetic_payload_writes={} uses_device_kv_cache={}; scheduler CUDA KV-attention resident_uploads={} resident_query_shapes={} resident_buffer_uses={} status={} launches={} hidden_projection_launches={} rows={} query_rows={} kv_descriptors={} output_bytes={} output_values={} finite_values={} nonzero_values={} output_checksum={} uses_device_kv_attention={} full_context_device_attention_complete={}; numeric scheduler progression passed={} source_rows={} visible_checksum={} rejected_mtp_checksum={} device_attention_output_delta_status={} device_attention_output_delta_rows={} device_attention_output_delta_values={} device_attention_output_delta_checksum={} device_attention_output_delta_backend={} device_attention_output_delta_device_prefix_rows={} device_attention_output_delta_device_prefix_values={} device_attention_output_delta_device_prefix_backend={} uses_device_attention_output_delta={} device_delta_template_status={} device_delta_template_uploads={} device_delta_template_uses={} device_delta_template_resident_values={} device_mlp_delta_status={} device_mlp_delta_rows={} device_mlp_delta_values={} device_mlp_delta_checksum={} device_mlp_delta_backend={} device_mlp_weight_uploads={} device_mlp_weight_resident_values={} uses_device_mlp_delta={} device_real_dense_mlp_delta_status={} device_real_dense_mlp_delta_rows={} device_real_dense_mlp_delta_values={} device_real_dense_mlp_delta_checksum={} device_real_dense_mlp_delta_backend={} device_real_dense_mlp_norm_backend={} device_real_dense_mlp_weight_tensors={} device_real_dense_mlp_weight_bytes={} device_real_dense_mlp_layers={} device_real_dense_mlp_source_segments={} uses_device_real_dense_mlp_delta={} device_real_sparse_shared_mlp_delta_status={} device_real_sparse_shared_mlp_delta_rows={} device_real_sparse_shared_mlp_delta_values={} device_real_sparse_shared_mlp_delta_checksum={} device_real_sparse_shared_mlp_delta_backend={} device_real_sparse_shared_mlp_norm_backend={} device_real_sparse_shared_mlp_weight_tensors={} device_real_sparse_shared_mlp_weight_bytes={} device_real_sparse_shared_mlp_layers={} device_real_sparse_shared_mlp_source_segments={} uses_device_real_sparse_shared_mlp_delta={} device_real_sparse_routed_mlp_delta_status={} device_real_sparse_routed_mlp_delta_rows={} device_real_sparse_routed_mlp_delta_values={} device_real_sparse_routed_mlp_delta_checksum={} device_real_sparse_routed_mlp_delta_backend={} device_real_sparse_routed_mlp_route_backend={} device_real_sparse_routed_mlp_router_backend={} device_real_sparse_routed_mlp_routes={} device_real_sparse_routed_mlp_router_weight_bytes={} device_real_sparse_routed_mlp_router_bias_bytes={} device_real_sparse_routed_mlp_route_cache_cuda_entries={} device_real_sparse_routed_mlp_route_cache_cuda_uploads={} device_real_sparse_routed_mlp_route_cache_cuda_hits={} device_real_sparse_routed_mlp_router_cache_entries={} device_real_sparse_routed_mlp_router_cache_hits={} device_real_sparse_routed_mlp_layers={} device_real_sparse_routed_mlp_source_segments={} uses_device_real_sparse_routed_mlp_delta={} device_hidden_segment_status={} device_hidden_segment_residual_adds={} device_hidden_segment_updates={} device_hidden_segment_resident_segments={} device_hidden_segment_resident_values={} device_hidden_segment_final_checksum={} expected_device_hidden_segment_final_checksum={} uses_device_hidden_segment_residual_add={}; legacy mixed scheduler-row NVFP4 probe status={} passed={} row_mode={} source_rows={}/{} layers={} routes={} residual_adds={} output_rows={} covers_full_output_rows={} covers_sources={} final_checksum={:?}, but the live scheduler trace does not yet drive full real-checkpoint attention/MLP/sampling residual execution for all rows",
                scheduler_real_tensor_catalog_available,
                scheduler_execution_dry_run.sparse_expert_host_batch_sets,
                scheduler_execution_dry_run.sparse_expert_host_batches,
                scheduler_execution_dry_run.sparse_expert_host_batch_rows,
                scheduler_execution_dry_run.sparse_expert_host_batch_routes,
                scheduler_execution_dry_run.sparse_expert_host_batch_expert_tiles,
                scheduler_execution_dry_run.sparse_expert_host_batch_routes_match_global,
                scheduler_execution_dry_run.sparse_expert_host_batch_graph_counts_valid,
                scheduler_execution_dry_run.sparse_expert_host_request_frames,
                scheduler_execution_dry_run.sparse_expert_host_request_rows,
                scheduler_execution_dry_run.sparse_expert_host_request_routes,
                scheduler_execution_dry_run.sparse_expert_host_request_payload_bytes,
                scheduler_execution_dry_run.sparse_expert_host_request_wire_bytes,
                scheduler_execution_dry_run.sparse_expert_host_response_frames,
                scheduler_execution_dry_run.sparse_expert_host_response_rows,
                scheduler_execution_dry_run.sparse_expert_host_response_payload_bytes,
                scheduler_execution_dry_run.sparse_expert_host_response_wire_bytes,
                scheduler_execution_dry_run.sparse_expert_host_wire_envelopes_valid,
                scheduler_execution_dry_run.device_kv_status,
                scheduler_execution_dry_run.device_kv_writes,
                scheduler_execution_dry_run.device_kv_reads,
                scheduler_execution_dry_run.device_kv_bytes,
                scheduler_execution_dry_run.projected_device_kv_writes,
                scheduler_execution_dry_run.projected_device_kv_write_bytes,
                scheduler_execution_dry_run.synthetic_kv_payload_writes,
                scheduler_execution_dry_run.uses_device_kv_cache,
                scheduler_execution_dry_run.device_attention_resident_uploads,
                scheduler_execution_dry_run.device_attention_resident_query_shapes,
                scheduler_execution_dry_run.device_attention_resident_buffer_uses,
                scheduler_execution_dry_run.device_attention_status,
                scheduler_execution_dry_run.device_attention_launches,
                scheduler_execution_dry_run.device_attention_hidden_projection_launches,
                scheduler_execution_dry_run.device_attention_rows,
                scheduler_execution_dry_run.device_attention_query_rows,
                scheduler_execution_dry_run.device_attention_kv_descriptors,
                scheduler_execution_dry_run.device_attention_output_bytes,
                scheduler_execution_dry_run.device_attention_output_values,
                scheduler_execution_dry_run.device_attention_output_finite_values,
                scheduler_execution_dry_run.device_attention_output_nonzero_values,
                scheduler_execution_dry_run.device_attention_output_checksum,
                scheduler_execution_dry_run.uses_device_kv_attention,
                scheduler_execution_dry_run.full_context_device_attention_complete,
                scheduler_execution_dry_run.numeric_progression_self_test.passed,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .unique_source_rows,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .final_visible_checksum,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .rejected_mtp_checksum,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_attention_output_delta_status,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .attention_device_output_delta_rows,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .attention_device_output_delta_values,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .attention_device_output_delta_checksum,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .attention_device_output_delta_backend,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .attention_device_output_delta_device_prefix_rows,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .attention_device_output_delta_device_prefix_values,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .attention_device_output_delta_device_prefix_backend,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .uses_device_attention_output_delta,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_delta_template_status,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_delta_template_uploads,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_delta_template_uses,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_delta_template_resident_values,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_mlp_delta_status,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_mlp_delta_rows,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_mlp_delta_values,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_mlp_delta_checksum,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_mlp_delta_backend,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_mlp_weight_uploads,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_mlp_weight_resident_values,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .uses_device_mlp_delta,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_real_dense_mlp_delta_status,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_real_dense_mlp_delta_rows,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_real_dense_mlp_delta_values,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_real_dense_mlp_delta_checksum,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_real_dense_mlp_delta_backend,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_real_dense_mlp_norm_backend,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_real_dense_mlp_weight_tensors,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_real_dense_mlp_weight_bytes,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_real_dense_mlp_layers,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_real_dense_mlp_source_segments,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .uses_device_real_dense_mlp_delta,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_real_sparse_shared_mlp_delta_status,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_real_sparse_shared_mlp_delta_rows,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_real_sparse_shared_mlp_delta_values,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_real_sparse_shared_mlp_delta_checksum,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_real_sparse_shared_mlp_delta_backend,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_real_sparse_shared_mlp_norm_backend,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_real_sparse_shared_mlp_weight_tensors,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_real_sparse_shared_mlp_weight_bytes,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_real_sparse_shared_mlp_layers,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_real_sparse_shared_mlp_source_segments,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .uses_device_real_sparse_shared_mlp_delta,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_real_sparse_routed_mlp_delta_status,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_real_sparse_routed_mlp_delta_rows,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_real_sparse_routed_mlp_delta_values,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_real_sparse_routed_mlp_delta_checksum,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_real_sparse_routed_mlp_delta_backend,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_real_sparse_routed_mlp_route_backend,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_real_sparse_routed_mlp_router_backend,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_real_sparse_routed_mlp_routes,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_real_sparse_routed_mlp_router_weight_bytes,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_real_sparse_routed_mlp_router_bias_bytes,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_real_sparse_routed_mlp_route_cache_cuda_entries,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_real_sparse_routed_mlp_route_cache_cuda_uploads,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_real_sparse_routed_mlp_route_cache_cuda_hits,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_real_sparse_routed_mlp_router_cache_entries,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_real_sparse_routed_mlp_router_cache_hits,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_real_sparse_routed_mlp_layers,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_real_sparse_routed_mlp_source_segments,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .uses_device_real_sparse_routed_mlp_delta,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_hidden_segment_status,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_hidden_segment_residual_adds,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_hidden_segment_value_updates,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_hidden_segment_resident_segments,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_hidden_segment_resident_values,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .device_hidden_segment_final_checksum,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .expected_device_hidden_segment_final_checksum,
                scheduler_execution_dry_run
                    .numeric_progression_self_test
                    .uses_device_hidden_segment_residual_add,
                expert_scheduler_rows_probe.status,
                expert_scheduler_rows_probe.passed,
                expert_scheduler_rows_probe.row_mode,
                expert_scheduler_rows_probe.source_rows_executed,
                expert_scheduler_rows_probe.planned_compatible_batch_rows,
                expert_scheduler_rows_probe.layers_executed,
                expert_scheduler_rows_probe.routes_executed,
                expert_scheduler_rows_probe.residual_adds,
                expert_scheduler_rows_probe.output_rows,
                expert_scheduler_rows_probe.covers_full_output_rows,
                expert_scheduler_rows_probe.covers_scheduler_source_modes,
                expert_scheduler_rows_probe.final_residual_checksum
            ),
            blocker: Some(
                "needs live coordinator-owned decode/prefill/MTP progression to execute real full-model tensors",
            ),
        },
        RealFullRequirement {
            name: "full_vocab_sampling",
            passed: false,
            evidence: format!(
                "BF16 lm_head coordinator scorer is wired through real chunk probes; real lm_head dry-run covers {} rows; default real lm_head chunk probe status={} passed={} rows={} bytes={} logits_backend={:?} argmax_backend={:?} sampler_backend={:?} sample_top_k={:?} sample_top_p={:?} sample_temperature={:?} top_token={:?} sampled_token={:?} top_logit={:?} sampled_score={:?}; guarded real lm_head full-vocab probe status={} passed={} rows={} sampler_backend={:?} sample_top_k={:?} sample_top_p={:?} sample_temperature={:?} sampled_token={:?} uses_full_model_residual={} uses_real_attention_prefix={} attention_rows={} attention_adds={} includes_causal_softmax={} includes_mla_softmax={} uses_real_dense_prefix={} uses_real_nvfp4_residual_prefix={} uses_real_nvfp4_residual_chain={} uses_real_sparse_mlp_shared_chain={} dense_layers={} dense_adds={} covers_all_dense_layers={} sparse_layers={} sparse_adds={} total_adds={} shared_layers={} shared_weight_bytes={} covers_all_sparse_layers={} residual_prefix_values={} residual_after_checksum={:?}; full-width live full-model residual outputs are not yet scored through the real lm_head",
                sampling_dry_run.vocab_size,
                sampling_dry_run.real_lm_head_default_chunk_probe.status,
                sampling_dry_run.real_lm_head_default_chunk_probe.passed,
                sampling_dry_run.real_lm_head_default_chunk_probe.rows_scored,
                sampling_dry_run
                    .real_lm_head_default_chunk_probe
                    .lm_head_bytes_read,
                sampling_dry_run
                    .real_lm_head_default_chunk_probe
                    .logits_kernel_backend,
                sampling_dry_run
                    .real_lm_head_default_chunk_probe
                    .argmax_kernel_backend,
                sampling_dry_run
                    .real_lm_head_default_chunk_probe
                    .sampler_kernel_backend,
                sampling_dry_run
                    .real_lm_head_default_chunk_probe
                    .sample_top_k,
                sampling_dry_run
                    .real_lm_head_default_chunk_probe
                    .sample_top_p,
                sampling_dry_run
                    .real_lm_head_default_chunk_probe
                    .sample_temperature,
                sampling_dry_run
                    .real_lm_head_default_chunk_probe
                    .top_token_id,
                sampling_dry_run
                    .real_lm_head_default_chunk_probe
                    .sampled_token_id,
                sampling_dry_run
                    .real_lm_head_default_chunk_probe
                    .top_logit,
                sampling_dry_run
                    .real_lm_head_default_chunk_probe
                    .sampled_score,
                sampling_real_lm_head_probe.status,
                sampling_real_lm_head_probe.passed,
                sampling_real_lm_head_probe.logits_evaluated,
                sampling_real_lm_head_probe.sampler_kernel_backend,
                sampling_real_lm_head_probe.sample_top_k,
                sampling_real_lm_head_probe.sample_top_p,
                sampling_real_lm_head_probe.sample_temperature,
                sampling_real_lm_head_probe.sampled_token_id,
                sampling_real_lm_head_probe.uses_full_model_residual,
                sampling_real_lm_head_probe.uses_real_attention_prefix,
                sampling_real_lm_head_probe.residual_source_attention_rows,
                sampling_real_lm_head_probe.residual_source_attention_residual_adds,
                sampling_real_lm_head_probe.residual_source_includes_causal_softmax,
                sampling_real_lm_head_probe.residual_source_includes_mla_softmax,
                sampling_real_lm_head_probe.uses_real_dense_prefix,
                sampling_real_lm_head_probe.uses_real_nvfp4_residual_prefix,
                sampling_real_lm_head_probe.uses_real_nvfp4_residual_chain,
                sampling_real_lm_head_probe.uses_real_sparse_mlp_shared_chain,
                sampling_real_lm_head_probe.residual_source_dense_layers,
                sampling_real_lm_head_probe.residual_source_dense_residual_adds,
                sampling_real_lm_head_probe.residual_source_covers_all_dense_layers,
                sampling_real_lm_head_probe.residual_source_sparse_layers,
                sampling_real_lm_head_probe.residual_source_residual_adds,
                sampling_real_lm_head_probe.residual_source_total_residual_adds,
                sampling_real_lm_head_probe.residual_source_shared_expert_layers,
                sampling_real_lm_head_probe.residual_source_shared_weight_bytes_read,
                sampling_real_lm_head_probe.residual_source_covers_all_sparse_layers,
                sampling_real_lm_head_probe.residual_prefix_values,
                sampling_real_lm_head_probe.residual_after_checksum
            ),
            blocker: Some(
                "needs numeric full-vocabulary logits over real full-model residual outputs and a live sampling path",
            ),
        },
    ]
}
