use serde::Serialize;

mod chains;

pub(in crate::commands::real_full) use chains::*;

#[derive(Debug, Serialize)]
pub(in crate::commands::real_full) struct RealFullExpertExecutionDryRun {
    pub(in crate::commands::real_full) status: &'static str,
    pub(in crate::commands::real_full) scope: &'static str,
    pub(in crate::commands::real_full) sparse_layers: usize,
    pub(in crate::commands::real_full) routed_experts_per_layer: usize,
    pub(in crate::commands::real_full) expected_routed_experts: usize,
    pub(in crate::commands::real_full) catalog_experts_with_any_tensor: usize,
    pub(in crate::commands::real_full) experts_with_weight_tensors: usize,
    pub(in crate::commands::real_full) experts_with_quant_metadata: usize,
    pub(in crate::commands::real_full) fully_covered_experts: usize,
    pub(in crate::commands::real_full) missing_weight_experts: usize,
    pub(in crate::commands::real_full) missing_quant_metadata_experts: usize,
    pub(in crate::commands::real_full) covered_sparse_layers: usize,
    pub(in crate::commands::real_full) routed_weight_tensors: usize,
    pub(in crate::commands::real_full) routed_quant_metadata_tensors: usize,
    pub(in crate::commands::real_full) routed_weight_bytes: u64,
    pub(in crate::commands::real_full) routed_quant_metadata_bytes: u64,
    pub(in crate::commands::real_full) placement_policy: &'static str,
    pub(in crate::commands::real_full) owner_partitions: Vec<RealFullExpertOwnerPartition>,
    pub(in crate::commands::real_full) planned_sparse_expert_batches: usize,
    pub(in crate::commands::real_full) planned_expert_batch_rows: usize,
    pub(in crate::commands::real_full) planned_route_entries: usize,
    pub(in crate::commands::real_full) planned_expert_source_modes: [&'static str; 3],
    pub(in crate::commands::real_full) planned_prefill_expert_rows: usize,
    pub(in crate::commands::real_full) planned_decode_expert_rows: usize,
    pub(in crate::commands::real_full) planned_mtp_verify_expert_rows: usize,
    pub(in crate::commands::real_full) planned_prefill_route_entries: usize,
    pub(in crate::commands::real_full) planned_decode_route_entries: usize,
    pub(in crate::commands::real_full) planned_mtp_verify_route_entries: usize,
    pub(in crate::commands::real_full) planned_source_modes_covered: bool,
    pub(in crate::commands::real_full) planned_route_entries_match_source_rows: bool,
    pub(in crate::commands::real_full) hidden_dim: usize,
    pub(in crate::commands::real_full) hidden_bytes_per_row: usize,
    pub(in crate::commands::real_full) logical_hidden_row_bytes: usize,
    pub(in crate::commands::real_full) logical_partial_output_row_bytes: usize,
    pub(in crate::commands::real_full) route_entries_per_row: usize,
    pub(in crate::commands::real_full) max_touched_hosts_per_batch: usize,
    pub(in crate::commands::real_full) all_sparse_layers_have_all_experts: bool,
    pub(in crate::commands::real_full) all_experts_have_weight_tensors: bool,
    pub(in crate::commands::real_full) all_experts_have_quant_metadata: bool,
    pub(in crate::commands::real_full) real_nvfp4_numeric_probe: RealFullExpertRealNvfp4Probe,
    pub(in crate::commands::real_full) real_nvfp4_all_layer_probe: RealFullExpertAllLayerNvfp4Probe,
    pub(in crate::commands::real_full) real_nvfp4_residual_chain_probe:
        RealFullExpertResidualChainNvfp4Probe,
    pub(in crate::commands::real_full) real_sparse_mlp_shared_chain_probe:
        RealFullExpertSparseMlpSharedChainProbe,
    pub(in crate::commands::real_full) real_nvfp4_scheduler_rows_probe:
        RealFullExpertSchedulerRowsNvfp4Probe,
    pub(in crate::commands::real_full) numeric_execution_implemented: bool,
}

#[derive(Debug, Serialize)]
pub(in crate::commands::real_full) struct RealFullExpertRealNvfp4Probe {
    pub(in crate::commands::real_full) status: &'static str,
    pub(in crate::commands::real_full) scope: &'static str,
    pub(in crate::commands::real_full) opt_in_env: &'static str,
    pub(in crate::commands::real_full) hidden_source: &'static str,
    pub(in crate::commands::real_full) quant_recipe: &'static str,
    pub(in crate::commands::real_full) layer_id: usize,
    pub(in crate::commands::real_full) expert_id: usize,
    pub(in crate::commands::real_full) hidden_dim: usize,
    pub(in crate::commands::real_full) top_k: usize,
    pub(in crate::commands::real_full) route_count: usize,
    pub(in crate::commands::real_full) router_weight_bytes_read: u64,
    pub(in crate::commands::real_full) router_bias_bytes_read: u64,
    pub(in crate::commands::real_full) row_mode: &'static str,
    pub(in crate::commands::real_full) intermediate_rows: usize,
    pub(in crate::commands::real_full) output_rows: usize,
    pub(in crate::commands::real_full) covers_full_intermediate_rows: bool,
    pub(in crate::commands::real_full) covers_full_output_rows: bool,
    pub(in crate::commands::real_full) weight_tensors_read: usize,
    pub(in crate::commands::real_full) quant_metadata_tensors_read: usize,
    pub(in crate::commands::real_full) weight_bytes_read: u64,
    pub(in crate::commands::real_full) quant_metadata_bytes_read: u64,
    pub(in crate::commands::real_full) gate_checksum: Option<f64>,
    pub(in crate::commands::real_full) up_checksum: Option<f64>,
    pub(in crate::commands::real_full) activation_checksum: Option<f64>,
    pub(in crate::commands::real_full) output_checksum: Option<f64>,
    pub(in crate::commands::real_full) output_l2_norm: Option<f32>,
    pub(in crate::commands::real_full) first_output: Option<f32>,
    pub(in crate::commands::real_full) last_output: Option<f32>,
    pub(in crate::commands::real_full) reduced_output_checksum: Option<f64>,
    pub(in crate::commands::real_full) reduced_output_l2_norm: Option<f32>,
    pub(in crate::commands::real_full) reduced_first_output: Option<f32>,
    pub(in crate::commands::real_full) reduced_last_output: Option<f32>,
    pub(in crate::commands::real_full) residual_prefix_values: usize,
    pub(in crate::commands::real_full) residual_before_checksum: Option<f64>,
    pub(in crate::commands::real_full) residual_delta_checksum: Option<f64>,
    pub(in crate::commands::real_full) residual_after_checksum: Option<f64>,
    pub(in crate::commands::real_full) residual_first_before: Option<f32>,
    pub(in crate::commands::real_full) residual_first_after: Option<f32>,
    pub(in crate::commands::real_full) residual_last_before: Option<f32>,
    pub(in crate::commands::real_full) residual_last_after: Option<f32>,
    pub(in crate::commands::real_full) routes: Vec<RealFullExpertRealNvfp4RouteProbe>,
    pub(in crate::commands::real_full) uses_real_nvfp4_weights: bool,
    pub(in crate::commands::real_full) uses_real_router: bool,
    pub(in crate::commands::real_full) applies_mlp_residual_prefix: bool,
    pub(in crate::commands::real_full) uses_full_model_residual: bool,
    pub(in crate::commands::real_full) covers_full_top_k: bool,
    pub(in crate::commands::real_full) covers_all_sparse_layers: bool,
    pub(in crate::commands::real_full) covers_all_experts: bool,
    pub(in crate::commands::real_full) passed: bool,
    pub(in crate::commands::real_full) skipped_reason: Option<String>,
}

#[derive(Debug, Serialize)]
pub(in crate::commands::real_full) struct RealFullExpertRealNvfp4RouteProbe {
    pub(in crate::commands::real_full) expert_id: usize,
    pub(in crate::commands::real_full) owner: String,
    pub(in crate::commands::real_full) score: f32,
    pub(in crate::commands::real_full) corrected_score: f32,
    pub(in crate::commands::real_full) normalized_weight: f32,
    pub(in crate::commands::real_full) gate_checksum: f64,
    pub(in crate::commands::real_full) up_checksum: f64,
    pub(in crate::commands::real_full) activation_checksum: f64,
    pub(in crate::commands::real_full) output_checksum: f64,
    pub(in crate::commands::real_full) output_l2_norm: f32,
    pub(in crate::commands::real_full) first_output: f32,
    pub(in crate::commands::real_full) last_output: f32,
}

#[derive(Debug, Serialize)]
pub(in crate::commands::real_full) struct RealFullExpertAllLayerNvfp4Probe {
    pub(in crate::commands::real_full) status: &'static str,
    pub(in crate::commands::real_full) scope: &'static str,
    pub(in crate::commands::real_full) opt_in_env: &'static str,
    pub(in crate::commands::real_full) hidden_source: &'static str,
    pub(in crate::commands::real_full) quant_recipe: &'static str,
    pub(in crate::commands::real_full) sparse_layers: usize,
    pub(in crate::commands::real_full) layers_executed: usize,
    pub(in crate::commands::real_full) top_k_per_layer: usize,
    pub(in crate::commands::real_full) routes_executed: usize,
    pub(in crate::commands::real_full) intermediate_rows: usize,
    pub(in crate::commands::real_full) output_rows: usize,
    pub(in crate::commands::real_full) router_weight_bytes_read: u64,
    pub(in crate::commands::real_full) router_bias_bytes_read: u64,
    pub(in crate::commands::real_full) weight_tensors_read: usize,
    pub(in crate::commands::real_full) quant_metadata_tensors_read: usize,
    pub(in crate::commands::real_full) weight_bytes_read: u64,
    pub(in crate::commands::real_full) quant_metadata_bytes_read: u64,
    pub(in crate::commands::real_full) output_checksum: Option<f64>,
    pub(in crate::commands::real_full) output_l2_norm: Option<f32>,
    pub(in crate::commands::real_full) first_layer_id: Option<usize>,
    pub(in crate::commands::real_full) last_layer_id: Option<usize>,
    pub(in crate::commands::real_full) first_expert_id: Option<usize>,
    pub(in crate::commands::real_full) last_expert_id: Option<usize>,
    pub(in crate::commands::real_full) layer_summaries: Vec<RealFullExpertAllLayerNvfp4LayerProbe>,
    pub(in crate::commands::real_full) uses_real_nvfp4_weights: bool,
    pub(in crate::commands::real_full) uses_real_router: bool,
    pub(in crate::commands::real_full) covers_all_sparse_layers: bool,
    pub(in crate::commands::real_full) covers_full_top_k: bool,
    pub(in crate::commands::real_full) covers_all_experts: bool,
    pub(in crate::commands::real_full) uses_full_model_residual: bool,
    pub(in crate::commands::real_full) passed: bool,
    pub(in crate::commands::real_full) skipped_reason: Option<String>,
}

#[derive(Debug, Serialize)]
pub(in crate::commands::real_full) struct RealFullExpertAllLayerNvfp4LayerProbe {
    pub(in crate::commands::real_full) layer_id: usize,
    pub(in crate::commands::real_full) expert_id: usize,
    pub(in crate::commands::real_full) owner: String,
    pub(in crate::commands::real_full) score: f32,
    pub(in crate::commands::real_full) corrected_score: f32,
    pub(in crate::commands::real_full) output_checksum: f64,
    pub(in crate::commands::real_full) output_l2_norm: f32,
    pub(in crate::commands::real_full) first_output: f32,
    pub(in crate::commands::real_full) last_output: f32,
}

#[derive(Debug, Serialize)]
pub(in crate::commands::real_full) struct RealFullExpertSchedulerRowsNvfp4Probe {
    pub(in crate::commands::real_full) status: &'static str,
    pub(in crate::commands::real_full) scope: &'static str,
    pub(in crate::commands::real_full) opt_in_env: &'static str,
    pub(in crate::commands::real_full) hidden_source: &'static str,
    pub(in crate::commands::real_full) quant_recipe: &'static str,
    pub(in crate::commands::real_full) row_mode: &'static str,
    pub(in crate::commands::real_full) source_modes: Vec<&'static str>,
    pub(in crate::commands::real_full) source_rows_executed: usize,
    pub(in crate::commands::real_full) planned_compatible_batch_rows: usize,
    pub(in crate::commands::real_full) planned_source_rows: usize,
    pub(in crate::commands::real_full) planned_decode_source_rows: usize,
    pub(in crate::commands::real_full) planned_prefill_source_rows: usize,
    pub(in crate::commands::real_full) planned_mtp_verify_source_rows: usize,
    pub(in crate::commands::real_full) executed_decode_source_rows: usize,
    pub(in crate::commands::real_full) executed_prefill_source_rows: usize,
    pub(in crate::commands::real_full) executed_mtp_verify_source_rows: usize,
    pub(in crate::commands::real_full) source_row_window_start: usize,
    pub(in crate::commands::real_full) source_row_window_end: usize,
    pub(in crate::commands::real_full) uses_source_row_window: bool,
    pub(in crate::commands::real_full) uses_full_scheduler_rows: bool,
    pub(in crate::commands::real_full) covers_all_scheduler_rows: bool,
    pub(in crate::commands::real_full) sparse_layers: usize,
    pub(in crate::commands::real_full) layers_executed: usize,
    pub(in crate::commands::real_full) top_k_per_layer: usize,
    pub(in crate::commands::real_full) routes_executed: usize,
    pub(in crate::commands::real_full) intermediate_rows: usize,
    pub(in crate::commands::real_full) output_rows: usize,
    pub(in crate::commands::real_full) covers_full_output_rows: bool,
    pub(in crate::commands::real_full) residual_prefix_values_per_row: usize,
    pub(in crate::commands::real_full) residual_adds: usize,
    pub(in crate::commands::real_full) router_weight_bytes_read: u64,
    pub(in crate::commands::real_full) router_bias_bytes_read: u64,
    pub(in crate::commands::real_full) weight_tensors_read: usize,
    pub(in crate::commands::real_full) quant_metadata_tensors_read: usize,
    pub(in crate::commands::real_full) weight_bytes_read: u64,
    pub(in crate::commands::real_full) quant_metadata_bytes_read: u64,
    pub(in crate::commands::real_full) router_cache_entries: usize,
    pub(in crate::commands::real_full) router_cache_hits: usize,
    pub(in crate::commands::real_full) router_tensor_loads: usize,
    pub(in crate::commands::real_full) route_projection_cache_entries: usize,
    pub(in crate::commands::real_full) route_projection_cache_hits: usize,
    pub(in crate::commands::real_full) route_projection_loads: usize,
    pub(in crate::commands::real_full) requested_parallelism: usize,
    pub(in crate::commands::real_full) worker_count: usize,
    pub(in crate::commands::real_full) row_chunks: usize,
    pub(in crate::commands::real_full) output_checksum: Option<f64>,
    pub(in crate::commands::real_full) output_l2_norm: Option<f32>,
    pub(in crate::commands::real_full) initial_residual_checksum: Option<f64>,
    pub(in crate::commands::real_full) residual_delta_checksum: Option<f64>,
    pub(in crate::commands::real_full) final_residual_checksum: Option<f64>,
    pub(in crate::commands::real_full) first_layer_id: Option<usize>,
    pub(in crate::commands::real_full) last_layer_id: Option<usize>,
    pub(in crate::commands::real_full) row_summaries: Vec<RealFullExpertSchedulerRowNvfp4Probe>,
    pub(in crate::commands::real_full) uses_real_nvfp4_weights: bool,
    pub(in crate::commands::real_full) uses_real_router: bool,
    pub(in crate::commands::real_full) applies_sparse_mlp_residual_chain: bool,
    pub(in crate::commands::real_full) covers_all_sparse_layers: bool,
    pub(in crate::commands::real_full) covers_full_top_k: bool,
    pub(in crate::commands::real_full) covers_decode_source: bool,
    pub(in crate::commands::real_full) covers_prefill_source: bool,
    pub(in crate::commands::real_full) covers_mtp_verify_source: bool,
    pub(in crate::commands::real_full) covers_scheduler_source_modes: bool,
    pub(in crate::commands::real_full) includes_attention: bool,
    pub(in crate::commands::real_full) includes_dense_layers: bool,
    pub(in crate::commands::real_full) includes_shared_expert: bool,
    pub(in crate::commands::real_full) uses_full_model_residual: bool,
    pub(in crate::commands::real_full) passed: bool,
    pub(in crate::commands::real_full) skipped_reason: Option<String>,
}

#[derive(Debug, Serialize)]
pub(in crate::commands::real_full) struct RealFullExpertSchedulerRowNvfp4Probe {
    pub(in crate::commands::real_full) source_mode: &'static str,
    pub(in crate::commands::real_full) source_row_index: usize,
    pub(in crate::commands::real_full) layers_executed: usize,
    pub(in crate::commands::real_full) routes_executed: usize,
    pub(in crate::commands::real_full) residual_adds: usize,
    pub(in crate::commands::real_full) initial_residual_checksum: f64,
    pub(in crate::commands::real_full) residual_delta_checksum: f64,
    pub(in crate::commands::real_full) final_residual_checksum: f64,
    pub(in crate::commands::real_full) output_checksum: f64,
    pub(in crate::commands::real_full) output_l2_norm: f32,
    pub(in crate::commands::real_full) first_expert_id: Option<usize>,
    pub(in crate::commands::real_full) last_expert_id: Option<usize>,
    pub(in crate::commands::real_full) first_residual_after: f32,
    pub(in crate::commands::real_full) last_residual_after: f32,
}

#[derive(Debug, Serialize)]
pub(in crate::commands::real_full) struct RealFullExpertOwnerPartition {
    pub(in crate::commands::real_full) owner: String,
    pub(in crate::commands::real_full) sparse_layers: usize,
    pub(in crate::commands::real_full) routed_experts: usize,
    pub(in crate::commands::real_full) routed_weight_tensors: usize,
    pub(in crate::commands::real_full) routed_quant_metadata_tensors: usize,
    pub(in crate::commands::real_full) routed_weight_bytes: u64,
    pub(in crate::commands::real_full) routed_quant_metadata_bytes: u64,
}
