use glmrt_core::{DType, TensorRole};
use serde::Serialize;

pub(in crate::commands::real_full) const REAL_FULL_RESIDUAL_COMPLETION_BLOCKER: &str =
    "full residual stream requires every completion gate to pass; inspect completion_gates.missing_gate_names for the current missing runtime stages";

#[derive(Debug, Serialize)]
pub(in crate::commands::real_full) struct RealFullResidualStreamDryRun {
    pub(in crate::commands::real_full) status: &'static str,
    pub(in crate::commands::real_full) scope: &'static str,
    pub(in crate::commands::real_full) layer_count: usize,
    pub(in crate::commands::real_full) row_count: usize,
    pub(in crate::commands::real_full) hidden_dim: usize,
    pub(in crate::commands::real_full) hidden_bytes_per_row: usize,
    pub(in crate::commands::real_full) residual_state_bytes: usize,
    pub(in crate::commands::real_full) dense_layers: usize,
    pub(in crate::commands::real_full) sparse_layers: usize,
    pub(in crate::commands::real_full) remote_sparse_layers: usize,
    pub(in crate::commands::real_full) attention_residual_adds: usize,
    pub(in crate::commands::real_full) mlp_residual_adds: usize,
    pub(in crate::commands::real_full) total_residual_adds: usize,
    pub(in crate::commands::real_full) terminal_rows: usize,
    pub(in crate::commands::real_full) terminal_stages: Vec<&'static str>,
    pub(in crate::commands::real_full) final_residual_state_hash: u64,
    pub(in crate::commands::real_full) numeric_kernel_self_test: RealFullResidualKernelSelfTest,
    pub(in crate::commands::real_full) real_dense_prefix_probe: RealFullDensePrefixProbe,
    pub(in crate::commands::real_full) real_attention_residual_prefix_probe:
        RealFullAttentionResidualPrefixProbe,
    pub(in crate::commands::real_full) real_mla_rope_attention_probe: RealFullMlaRopeAttentionProbe,
    pub(in crate::commands::real_full) real_dsa_indexer_attention_probe:
        RealFullDsaIndexerAttentionProbe,
    pub(in crate::commands::real_full) real_attention_dense_sparse_prefix_probe:
        RealFullAttentionDenseSparsePrefixProbe,
    pub(in crate::commands::real_full) real_layer_ordered_prefix_probe:
        RealFullLayerOrderedResidualPrefixProbe,
    pub(in crate::commands::real_full) real_layer_ordered_execution_probe:
        RealFullLayerOrderedResidualExecutionProbe,
    pub(in crate::commands::real_full) layer_order_verified: bool,
    pub(in crate::commands::real_full) layer_dry_runs: Vec<RealFullResidualLayerDryRun>,
}

#[derive(Debug, Serialize)]
pub(in crate::commands::real_full) struct RealFullResidualKernelSelfTest {
    pub(in crate::commands::real_full) status: &'static str,
    pub(in crate::commands::real_full) scope: &'static str,
    pub(in crate::commands::real_full) layers: usize,
    pub(in crate::commands::real_full) rows: usize,
    pub(in crate::commands::real_full) hidden_dim: usize,
    pub(in crate::commands::real_full) residual_adds: usize,
    pub(in crate::commands::real_full) values_updated: usize,
    pub(in crate::commands::real_full) final_checksum: f32,
    pub(in crate::commands::real_full) expected_checksum: f32,
    pub(in crate::commands::real_full) first_value: f32,
    pub(in crate::commands::real_full) expected_first_value: f32,
    pub(in crate::commands::real_full) last_value: f32,
    pub(in crate::commands::real_full) expected_last_value: f32,
    pub(in crate::commands::real_full) passed: bool,
}

#[derive(Debug, Serialize)]
pub(in crate::commands::real_full) struct RealFullResidualLayerDryRun {
    pub(in crate::commands::real_full) layer_id: usize,
    pub(in crate::commands::real_full) layer_kind: &'static str,
    pub(in crate::commands::real_full) input_rows: usize,
    pub(in crate::commands::real_full) residual_state_bytes: usize,
    pub(in crate::commands::real_full) attention_input_norm: bool,
    pub(in crate::commands::real_full) attention_output_projection: bool,
    pub(in crate::commands::real_full) attention_residual_boundary: bool,
    pub(in crate::commands::real_full) post_attention_norm: bool,
    pub(in crate::commands::real_full) mlp_kind: &'static str,
    pub(in crate::commands::real_full) routed_expert_exchange: bool,
    pub(in crate::commands::real_full) mlp_residual_boundary: bool,
    pub(in crate::commands::real_full) output_rows: usize,
    pub(in crate::commands::real_full) residual_state_hash: u64,
    pub(in crate::commands::real_full) layer_order_verified: bool,
}

#[derive(Debug, Serialize)]
pub(in crate::commands::real_full) struct RealFullDensePrefixProbe {
    pub(in crate::commands::real_full) status: &'static str,
    pub(in crate::commands::real_full) scope: &'static str,
    pub(in crate::commands::real_full) opt_in_env: &'static str,
    pub(in crate::commands::real_full) row_mode: &'static str,
    pub(in crate::commands::real_full) hidden_source: &'static str,
    pub(in crate::commands::real_full) dense_layers: usize,
    pub(in crate::commands::real_full) layers_executed: usize,
    pub(in crate::commands::real_full) intermediate_rows: usize,
    pub(in crate::commands::real_full) output_rows: usize,
    pub(in crate::commands::real_full) residual_prefix_values: usize,
    pub(in crate::commands::real_full) residual_adds: usize,
    pub(in crate::commands::real_full) norm_tensors_read: usize,
    pub(in crate::commands::real_full) weight_tensors_read: usize,
    pub(in crate::commands::real_full) norm_bytes_read: u64,
    pub(in crate::commands::real_full) weight_bytes_read: u64,
    pub(in crate::commands::real_full) norm_checksum: Option<f64>,
    pub(in crate::commands::real_full) activation_checksum: Option<f64>,
    pub(in crate::commands::real_full) output_checksum: Option<f64>,
    pub(in crate::commands::real_full) output_l2_norm: Option<f32>,
    pub(in crate::commands::real_full) initial_residual_checksum: Option<f64>,
    pub(in crate::commands::real_full) residual_delta_checksum: Option<f64>,
    pub(in crate::commands::real_full) final_residual_checksum: Option<f64>,
    pub(in crate::commands::real_full) first_layer_id: Option<usize>,
    pub(in crate::commands::real_full) last_layer_id: Option<usize>,
    pub(in crate::commands::real_full) layer_summaries: Vec<RealFullDensePrefixLayerProbe>,
    pub(in crate::commands::real_full) uses_real_dense_weights: bool,
    pub(in crate::commands::real_full) applies_dense_mlp_residual_prefix: bool,
    pub(in crate::commands::real_full) includes_attention: bool,
    pub(in crate::commands::real_full) covers_all_dense_layers: bool,
    pub(in crate::commands::real_full) covers_full_output_rows: bool,
    pub(in crate::commands::real_full) uses_full_model_residual: bool,
    pub(in crate::commands::real_full) passed: bool,
    pub(in crate::commands::real_full) skipped_reason: Option<String>,
}

#[derive(Debug, Serialize)]
pub(in crate::commands::real_full) struct RealFullDensePrefixLayerProbe {
    pub(in crate::commands::real_full) layer_id: usize,
    pub(in crate::commands::real_full) norm_backend: &'static str,
    pub(in crate::commands::real_full) linear_backend: &'static str,
    pub(in crate::commands::real_full) mlp_backend: &'static str,
    pub(in crate::commands::real_full) norm_checksum: f64,
    pub(in crate::commands::real_full) norm_l2_norm: f32,
    pub(in crate::commands::real_full) activation_checksum: f64,
    pub(in crate::commands::real_full) output_checksum: f64,
    pub(in crate::commands::real_full) output_l2_norm: f32,
    pub(in crate::commands::real_full) residual_before_checksum: f64,
    pub(in crate::commands::real_full) residual_delta_checksum: f64,
    pub(in crate::commands::real_full) residual_after_checksum: f64,
    pub(in crate::commands::real_full) residual_add_backend: &'static str,
    pub(in crate::commands::real_full) first_residual_after: f32,
    pub(in crate::commands::real_full) last_residual_after: f32,
}

#[derive(Debug, Serialize)]
pub(in crate::commands::real_full) struct RealFullAttentionResidualPrefixProbe {
    pub(in crate::commands::real_full) status: &'static str,
    pub(in crate::commands::real_full) scope: &'static str,
    pub(in crate::commands::real_full) layer_id: usize,
    pub(in crate::commands::real_full) hidden_source: &'static str,
    pub(in crate::commands::real_full) context_source: &'static str,
    pub(in crate::commands::real_full) q_lora_rank: usize,
    pub(in crate::commands::real_full) kv_lora_rank: usize,
    pub(in crate::commands::real_full) attention_rows: usize,
    pub(in crate::commands::real_full) output_prefix_values: usize,
    pub(in crate::commands::real_full) residual_prefix_values: usize,
    pub(in crate::commands::real_full) residual_adds: usize,
    pub(in crate::commands::real_full) causal_attention_scores: usize,
    pub(in crate::commands::real_full) causal_softmax_rows: usize,
    pub(in crate::commands::real_full) input_norm_tensors_read: usize,
    pub(in crate::commands::real_full) attention_tensors_read: usize,
    pub(in crate::commands::real_full) input_norm_bytes_read: u64,
    pub(in crate::commands::real_full) projection_bytes_read: u64,
    pub(in crate::commands::real_full) o_proj_bytes_read: u64,
    pub(in crate::commands::real_full) projection_backend: &'static str,
    pub(in crate::commands::real_full) attention_backend: &'static str,
    pub(in crate::commands::real_full) residual_add_backend: &'static str,
    pub(in crate::commands::real_full) q_output_checksum: Option<f64>,
    pub(in crate::commands::real_full) kv_output_checksum: Option<f64>,
    pub(in crate::commands::real_full) kv_rope_checksum: Option<f64>,
    pub(in crate::commands::real_full) attention_output_checksum: Option<f64>,
    pub(in crate::commands::real_full) attention_output_l2_norm: Option<f32>,
    pub(in crate::commands::real_full) residual_before_checksum: Option<f64>,
    pub(in crate::commands::real_full) residual_delta_checksum: Option<f64>,
    pub(in crate::commands::real_full) residual_after_checksum: Option<f64>,
    pub(in crate::commands::real_full) first_residual_after: Option<f32>,
    pub(in crate::commands::real_full) last_residual_after: Option<f32>,
    pub(in crate::commands::real_full) uses_real_attention_weights: bool,
    pub(in crate::commands::real_full) applies_attention_residual_prefix: bool,
    pub(in crate::commands::real_full) includes_causal_softmax: bool,
    pub(in crate::commands::real_full) includes_mla_softmax: bool,
    pub(in crate::commands::real_full) uses_full_model_residual: bool,
    pub(in crate::commands::real_full) passed: bool,
    pub(in crate::commands::real_full) skipped_reason: Option<String>,
}

#[derive(Debug, Serialize)]
pub(in crate::commands::real_full) struct RealFullMlaRopeAttentionProbe {
    pub(in crate::commands::real_full) status: &'static str,
    pub(in crate::commands::real_full) scope: &'static str,
    pub(in crate::commands::real_full) layer_id: usize,
    pub(in crate::commands::real_full) hidden_source: &'static str,
    pub(in crate::commands::real_full) context_source: &'static str,
    pub(in crate::commands::real_full) attention_rows: usize,
    pub(in crate::commands::real_full) prefix_context_rows: usize,
    pub(in crate::commands::real_full) total_context_rows: usize,
    pub(in crate::commands::real_full) attention_heads: usize,
    pub(in crate::commands::real_full) q_lora_rank: usize,
    pub(in crate::commands::real_full) kv_lora_rank: usize,
    pub(in crate::commands::real_full) qk_nope_head_dim: usize,
    pub(in crate::commands::real_full) qk_rope_head_dim: usize,
    pub(in crate::commands::real_full) q_head_dim: usize,
    pub(in crate::commands::real_full) v_head_dim: usize,
    pub(in crate::commands::real_full) compressed_kv_width: usize,
    pub(in crate::commands::real_full) compressed_kv_values: usize,
    pub(in crate::commands::real_full) causal_attention_scores: usize,
    pub(in crate::commands::real_full) mla_softmax_rows: usize,
    pub(in crate::commands::real_full) attention_context_values: usize,
    pub(in crate::commands::real_full) output_prefix_values: usize,
    pub(in crate::commands::real_full) residual_prefix_values: usize,
    pub(in crate::commands::real_full) residual_adds: usize,
    pub(in crate::commands::real_full) rope_theta: f64,
    pub(in crate::commands::real_full) input_norm_bytes_read: u64,
    pub(in crate::commands::real_full) projection_bytes_read: u64,
    pub(in crate::commands::real_full) o_proj_bytes_read: u64,
    pub(in crate::commands::real_full) rope_backend: &'static str,
    pub(in crate::commands::real_full) attention_backend: &'static str,
    pub(in crate::commands::real_full) q_nope_checksum: Option<f64>,
    pub(in crate::commands::real_full) q_rope_checksum: Option<f64>,
    pub(in crate::commands::real_full) q_rope_rotated_checksum: Option<f64>,
    pub(in crate::commands::real_full) k_nope_checksum: Option<f64>,
    pub(in crate::commands::real_full) k_rope_checksum: Option<f64>,
    pub(in crate::commands::real_full) k_rope_rotated_checksum: Option<f64>,
    pub(in crate::commands::real_full) value_checksum: Option<f64>,
    pub(in crate::commands::real_full) attention_scores_checksum: Option<f64>,
    pub(in crate::commands::real_full) attention_weights_checksum: Option<f64>,
    pub(in crate::commands::real_full) attention_context_checksum: Option<f64>,
    pub(in crate::commands::real_full) attention_output_checksum: Option<f64>,
    pub(in crate::commands::real_full) attention_output_l2_norm: Option<f32>,
    pub(in crate::commands::real_full) residual_before_checksum: Option<f64>,
    pub(in crate::commands::real_full) residual_delta_checksum: Option<f64>,
    pub(in crate::commands::real_full) residual_after_checksum: Option<f64>,
    pub(in crate::commands::real_full) uses_real_attention_weights: bool,
    pub(in crate::commands::real_full) includes_rope: bool,
    pub(in crate::commands::real_full) includes_mla_softmax: bool,
    pub(in crate::commands::real_full) applies_attention_residual_prefix: bool,
    pub(in crate::commands::real_full) uses_full_model_residual: bool,
    pub(in crate::commands::real_full) passed: bool,
    pub(in crate::commands::real_full) skipped_reason: Option<String>,
}

#[derive(Debug, Serialize)]
pub(in crate::commands::real_full) struct RealFullDsaIndexerAttentionProbe {
    pub(in crate::commands::real_full) status: &'static str,
    pub(in crate::commands::real_full) scope: &'static str,
    pub(in crate::commands::real_full) layer_id: usize,
    pub(in crate::commands::real_full) hidden_source: &'static str,
    pub(in crate::commands::real_full) context_source: &'static str,
    pub(in crate::commands::real_full) attention_rows: usize,
    pub(in crate::commands::real_full) q_lora_rank: usize,
    pub(in crate::commands::real_full) dsa_query_dim: usize,
    pub(in crate::commands::real_full) dsa_value_width: usize,
    pub(in crate::commands::real_full) candidate_rows: usize,
    pub(in crate::commands::real_full) prefix_kv_candidate_rows: usize,
    pub(in crate::commands::real_full) kv_cache_candidate_bytes: usize,
    pub(in crate::commands::real_full) dsa_top_k: usize,
    pub(in crate::commands::real_full) selected_indices: Vec<usize>,
    pub(in crate::commands::real_full) score_order: Vec<usize>,
    pub(in crate::commands::real_full) causal_attention_scores: usize,
    pub(in crate::commands::real_full) dsa_softmax_rows: usize,
    pub(in crate::commands::real_full) attention_context_values: usize,
    pub(in crate::commands::real_full) rope_theta: f64,
    pub(in crate::commands::real_full) input_norm_bytes_read: u64,
    pub(in crate::commands::real_full) q_projection_bytes_read: u64,
    pub(in crate::commands::real_full) indexer_bytes_read: u64,
    pub(in crate::commands::real_full) projection_backend: &'static str,
    pub(in crate::commands::real_full) rope_backend: &'static str,
    pub(in crate::commands::real_full) q_checksum: Option<f64>,
    pub(in crate::commands::real_full) q_rope_rotated_checksum: Option<f64>,
    pub(in crate::commands::real_full) k_checksum: Option<f64>,
    pub(in crate::commands::real_full) k_norm_checksum: Option<f64>,
    pub(in crate::commands::real_full) k_rope_rotated_checksum: Option<f64>,
    pub(in crate::commands::real_full) value_checksum: Option<f64>,
    pub(in crate::commands::real_full) candidate_scores_checksum: Option<f64>,
    pub(in crate::commands::real_full) attention_weights_checksum: Option<f64>,
    pub(in crate::commands::real_full) attention_context_checksum: Option<f64>,
    pub(in crate::commands::real_full) uses_real_indexer_weights: bool,
    pub(in crate::commands::real_full) includes_rope: bool,
    pub(in crate::commands::real_full) includes_dsa_candidate_selection: bool,
    pub(in crate::commands::real_full) includes_dsa_softmax: bool,
    pub(in crate::commands::real_full) uses_full_model_residual: bool,
    pub(in crate::commands::real_full) passed: bool,
    pub(in crate::commands::real_full) skipped_reason: Option<String>,
}

#[derive(Debug, Serialize)]
pub(in crate::commands::real_full) struct RealFullAttentionDenseSparsePrefixProbe {
    pub(in crate::commands::real_full) status: &'static str,
    pub(in crate::commands::real_full) scope: &'static str,
    pub(in crate::commands::real_full) opt_in_env: &'static str,
    pub(in crate::commands::real_full) row_mode: &'static str,
    pub(in crate::commands::real_full) hidden_source: &'static str,
    pub(in crate::commands::real_full) attention_layer: usize,
    pub(in crate::commands::real_full) attention_rows: usize,
    pub(in crate::commands::real_full) attention_residual_adds: usize,
    pub(in crate::commands::real_full) dense_layers: usize,
    pub(in crate::commands::real_full) dense_residual_adds: usize,
    pub(in crate::commands::real_full) sparse_layers: usize,
    pub(in crate::commands::real_full) sparse_residual_adds: usize,
    pub(in crate::commands::real_full) shared_expert_layers: usize,
    pub(in crate::commands::real_full) total_residual_adds: usize,
    pub(in crate::commands::real_full) sparse_output_rows: usize,
    pub(in crate::commands::real_full) residual_prefix_values: usize,
    pub(in crate::commands::real_full) routed_top_k_per_layer: usize,
    pub(in crate::commands::real_full) routed_routes: usize,
    pub(in crate::commands::real_full) input_norm_bytes_read: u64,
    pub(in crate::commands::real_full) attention_projection_bytes_read: u64,
    pub(in crate::commands::real_full) attention_o_proj_bytes_read: u64,
    pub(in crate::commands::real_full) dense_norm_bytes_read: u64,
    pub(in crate::commands::real_full) dense_weight_bytes_read: u64,
    pub(in crate::commands::real_full) sparse_router_weight_bytes_read: u64,
    pub(in crate::commands::real_full) sparse_router_bias_bytes_read: u64,
    pub(in crate::commands::real_full) sparse_routed_weight_bytes_read: u64,
    pub(in crate::commands::real_full) sparse_routed_quant_metadata_bytes_read: u64,
    pub(in crate::commands::real_full) sparse_shared_weight_bytes_read: u64,
    pub(in crate::commands::real_full) initial_residual_checksum: Option<f64>,
    pub(in crate::commands::real_full) attention_residual_checksum: Option<f64>,
    pub(in crate::commands::real_full) dense_residual_checksum: Option<f64>,
    pub(in crate::commands::real_full) sparse_residual_checksum: Option<f64>,
    pub(in crate::commands::real_full) residual_delta_checksum: Option<f64>,
    pub(in crate::commands::real_full) includes_attention: bool,
    pub(in crate::commands::real_full) includes_causal_softmax: bool,
    pub(in crate::commands::real_full) includes_mla_softmax: bool,
    pub(in crate::commands::real_full) includes_dense_layers: bool,
    pub(in crate::commands::real_full) includes_sparse_mlp: bool,
    pub(in crate::commands::real_full) includes_shared_expert: bool,
    pub(in crate::commands::real_full) covers_all_dense_layers: bool,
    pub(in crate::commands::real_full) covers_all_sparse_layers: bool,
    pub(in crate::commands::real_full) covers_full_top_k: bool,
    pub(in crate::commands::real_full) covers_full_output_rows: bool,
    pub(in crate::commands::real_full) uses_full_model_residual: bool,
    pub(in crate::commands::real_full) passed: bool,
    pub(in crate::commands::real_full) skipped_reason: Option<String>,
}

#[derive(Debug, Serialize)]
pub(in crate::commands::real_full) struct RealFullLayerOrderedResidualPrefixProbe {
    pub(in crate::commands::real_full) status: &'static str,
    pub(in crate::commands::real_full) scope: &'static str,
    pub(in crate::commands::real_full) row_mode: &'static str,
    pub(in crate::commands::real_full) hidden_source: &'static str,
    pub(in crate::commands::real_full) layer_id: usize,
    pub(in crate::commands::real_full) attention_rows: usize,
    pub(in crate::commands::real_full) attention_residual_adds: usize,
    pub(in crate::commands::real_full) mlp_residual_adds: usize,
    pub(in crate::commands::real_full) total_residual_adds: usize,
    pub(in crate::commands::real_full) dense_rows: usize,
    pub(in crate::commands::real_full) dense_intermediate_rows: usize,
    pub(in crate::commands::real_full) dense_output_rows: usize,
    pub(in crate::commands::real_full) residual_prefix_values: usize,
    pub(in crate::commands::real_full) input_norm_bytes_read: u64,
    pub(in crate::commands::real_full) attention_projection_bytes_read: u64,
    pub(in crate::commands::real_full) attention_o_proj_bytes_read: u64,
    pub(in crate::commands::real_full) dense_norm_bytes_read: u64,
    pub(in crate::commands::real_full) dense_weight_bytes_read: u64,
    pub(in crate::commands::real_full) initial_residual_checksum: Option<f64>,
    pub(in crate::commands::real_full) attention_residual_checksum: Option<f64>,
    pub(in crate::commands::real_full) dense_residual_checksum: Option<f64>,
    pub(in crate::commands::real_full) residual_delta_checksum: Option<f64>,
    pub(in crate::commands::real_full) includes_attention: bool,
    pub(in crate::commands::real_full) includes_causal_softmax: bool,
    pub(in crate::commands::real_full) includes_mla_softmax: bool,
    pub(in crate::commands::real_full) includes_dense_mlp: bool,
    pub(in crate::commands::real_full) includes_sparse_mlp: bool,
    pub(in crate::commands::real_full) carries_attention_residual_into_mlp: bool,
    pub(in crate::commands::real_full) layer_order_verified: bool,
    pub(in crate::commands::real_full) uses_full_model_residual: bool,
    pub(in crate::commands::real_full) passed: bool,
    pub(in crate::commands::real_full) skipped_reason: Option<String>,
}

#[derive(Debug, Serialize)]
pub(in crate::commands::real_full) struct RealFullLayerOrderedResidualExecutionProbe {
    pub(in crate::commands::real_full) status: &'static str,
    pub(in crate::commands::real_full) scope: &'static str,
    pub(in crate::commands::real_full) row_mode: &'static str,
    pub(in crate::commands::real_full) hidden_source: &'static str,
    pub(in crate::commands::real_full) layer_count: usize,
    pub(in crate::commands::real_full) traced_layers: usize,
    pub(in crate::commands::real_full) input_token_id: Option<usize>,
    pub(in crate::commands::real_full) embedding_bytes_read: u64,
    pub(in crate::commands::real_full) embedding_residual_checksum: Option<f64>,
    pub(in crate::commands::real_full) embedding_kernel_backend: Option<&'static str>,
    pub(in crate::commands::real_full) embedding_device_resident: bool,
    pub(in crate::commands::real_full) trace_steps: usize,
    pub(in crate::commands::real_full) attention_steps_executed: usize,
    pub(in crate::commands::real_full) attention_steps_missing: usize,
    pub(in crate::commands::real_full) dense_mlp_steps_executed: usize,
    pub(in crate::commands::real_full) sparse_mlp_steps_executed: usize,
    pub(in crate::commands::real_full) shared_expert_steps_executed: usize,
    pub(in crate::commands::real_full) planned_residual_adds: usize,
    pub(in crate::commands::real_full) total_numeric_residual_adds: usize,
    pub(in crate::commands::real_full) residual_adds_missing: usize,
    pub(in crate::commands::real_full) residual_prefix_values: usize,
    pub(in crate::commands::real_full) routed_routes: usize,
    pub(in crate::commands::real_full) final_residual_checksum: Option<f64>,
    pub(in crate::commands::real_full) covers_all_dense_layers: bool,
    pub(in crate::commands::real_full) covers_all_sparse_layers: bool,
    pub(in crate::commands::real_full) covers_full_top_k: bool,
    pub(in crate::commands::real_full) covers_full_output_rows: bool,
    pub(in crate::commands::real_full) carries_attention_into_dense: bool,
    pub(in crate::commands::real_full) carries_dense_into_sparse: bool,
    pub(in crate::commands::real_full) full_residual_stream_complete: bool,
    pub(in crate::commands::real_full) uses_full_model_residual: bool,
    pub(in crate::commands::real_full) coordinator_graph_slots: usize,
    pub(in crate::commands::real_full) coordinator_graph_captured_graphs: usize,
    pub(in crate::commands::real_full) coordinator_graph_captures: usize,
    pub(in crate::commands::real_full) coordinator_graph_launches: usize,
    pub(in crate::commands::real_full) uses_graph_captured_coordinator_kernels: bool,
    pub(in crate::commands::real_full) scheduler_rows: RealFullLayerOrderedSchedulerRowsProbe,
    pub(in crate::commands::real_full) terminal_lm_head_sampling:
        RealFullLayerOrderedLmHeadSamplingProbe,
    pub(in crate::commands::real_full) completion_gates: RealFullResidualCompletionGates,
    pub(in crate::commands::real_full) full_residual_stream_blocker: Option<&'static str>,
    pub(in crate::commands::real_full) execution_stepper: RealFullResidualExecutionStepper,
    pub(in crate::commands::real_full) step_summaries:
        Vec<RealFullLayerOrderedResidualExecutionStep>,
    pub(in crate::commands::real_full) passed: bool,
    pub(in crate::commands::real_full) skipped_reason: Option<String>,
}

#[derive(Debug, Serialize)]
pub(in crate::commands::real_full) struct RealFullLayerOrderedSchedulerRowsProbe {
    pub(in crate::commands::real_full) status: &'static str,
    pub(in crate::commands::real_full) scope: &'static str,
    pub(in crate::commands::real_full) source_mode: &'static str,
    pub(in crate::commands::real_full) layer_count: usize,
    pub(in crate::commands::real_full) selected_layerwaves: usize,
    pub(in crate::commands::real_full) selected_rows: usize,
    pub(in crate::commands::real_full) row_sources: usize,
    pub(in crate::commands::real_full) selected_decode_rows: usize,
    pub(in crate::commands::real_full) selected_prefill_rows: usize,
    pub(in crate::commands::real_full) selected_mtp_rows: usize,
    pub(in crate::commands::real_full) deferred_layerwaves: usize,
    pub(in crate::commands::real_full) kv_read_blocks: usize,
    pub(in crate::commands::real_full) committed_kv_writes: usize,
    pub(in crate::commands::real_full) backed_kv_bytes: usize,
    pub(in crate::commands::real_full) device_kv_status: &'static str,
    pub(in crate::commands::real_full) device_kv_writes: usize,
    pub(in crate::commands::real_full) device_kv_reads: usize,
    pub(in crate::commands::real_full) device_kv_bytes: usize,
    pub(in crate::commands::real_full) uses_device_kv_cache: bool,
    pub(in crate::commands::real_full) layer_order_verified: bool,
    pub(in crate::commands::real_full) uses_live_scheduler_rows: bool,
    pub(in crate::commands::real_full) passed: bool,
    pub(in crate::commands::real_full) skipped_reason: Option<String>,
}

#[derive(Debug, Serialize)]
pub(in crate::commands::real_full) struct RealFullLayerOrderedLmHeadSamplingProbe {
    pub(in crate::commands::real_full) status: &'static str,
    pub(in crate::commands::real_full) scope: &'static str,
    pub(in crate::commands::real_full) hidden_source: &'static str,
    pub(in crate::commands::real_full) uses_real_lm_head: bool,
    pub(in crate::commands::real_full) uses_layer_ordered_residual: bool,
    pub(in crate::commands::real_full) uses_layer_ordered_full_output_residual: bool,
    pub(in crate::commands::real_full) uses_full_model_residual: bool,
    pub(in crate::commands::real_full) lm_head_tensor: Option<String>,
    pub(in crate::commands::real_full) hidden_dim: usize,
    pub(in crate::commands::real_full) vocab_size: usize,
    pub(in crate::commands::real_full) start_token_id: usize,
    pub(in crate::commands::real_full) chunk_rows: usize,
    pub(in crate::commands::real_full) rows_scored: usize,
    pub(in crate::commands::real_full) chunks_scored: usize,
    pub(in crate::commands::real_full) lm_head_bytes_read: u64,
    pub(in crate::commands::real_full) hidden_values: usize,
    pub(in crate::commands::real_full) hidden_bytes: usize,
    pub(in crate::commands::real_full) logits_evaluated: usize,
    pub(in crate::commands::real_full) multiply_accumulate_ops: u64,
    pub(in crate::commands::real_full) logits_kernel_backend: Option<&'static str>,
    pub(in crate::commands::real_full) argmax_kernel_backend: Option<&'static str>,
    pub(in crate::commands::real_full) sampler_kernel_backend: Option<&'static str>,
    pub(in crate::commands::real_full) covers_full_vocabulary: bool,
    pub(in crate::commands::real_full) top_token_id: Option<usize>,
    pub(in crate::commands::real_full) top_logit: Option<f32>,
    pub(in crate::commands::real_full) sampled_token_id: Option<usize>,
    pub(in crate::commands::real_full) sampled_score: Option<f32>,
    pub(in crate::commands::real_full) sample_random_uniform: Option<f32>,
    pub(in crate::commands::real_full) sample_temperature: Option<f32>,
    pub(in crate::commands::real_full) sample_top_k: Option<usize>,
    pub(in crate::commands::real_full) sample_top_p: Option<f32>,
    pub(in crate::commands::real_full) residual_after_checksum: Option<f64>,
    pub(in crate::commands::real_full) passed: bool,
    pub(in crate::commands::real_full) skipped_reason: Option<String>,
}

#[derive(Debug, Serialize)]
pub(in crate::commands::real_full) struct RealFullResidualExecutionStepper {
    pub(in crate::commands::real_full) status: &'static str,
    pub(in crate::commands::real_full) scope: &'static str,
    pub(in crate::commands::real_full) row_mode: &'static str,
    pub(in crate::commands::real_full) layer_count: usize,
    pub(in crate::commands::real_full) traced_layers: usize,
    pub(in crate::commands::real_full) trace_steps: usize,
    pub(in crate::commands::real_full) attention_steps_executed: usize,
    pub(in crate::commands::real_full) attention_steps_missing: usize,
    pub(in crate::commands::real_full) dense_mlp_steps_executed: usize,
    pub(in crate::commands::real_full) sparse_mlp_steps_executed: usize,
    pub(in crate::commands::real_full) shared_expert_steps_executed: usize,
    pub(in crate::commands::real_full) planned_residual_adds: usize,
    pub(in crate::commands::real_full) total_numeric_residual_adds: usize,
    pub(in crate::commands::real_full) residual_adds_missing: usize,
    pub(in crate::commands::real_full) residual_prefix_values: usize,
    pub(in crate::commands::real_full) routed_routes: usize,
    pub(in crate::commands::real_full) stage_sources_recorded: usize,
    pub(in crate::commands::real_full) stage_statuses_recorded: usize,
    pub(in crate::commands::real_full) real_stage_count: usize,
    pub(in crate::commands::real_full) synthetic_stage_count: usize,
    pub(in crate::commands::real_full) provisional_stage_count: usize,
    pub(in crate::commands::real_full) blocked_stage_count: usize,
    pub(in crate::commands::real_full) coordinator_stage_count: usize,
    pub(in crate::commands::real_full) coordinator_cuda_stage_count: usize,
    pub(in crate::commands::real_full) coordinator_cpu_stage_count: usize,
    pub(in crate::commands::real_full) coordinator_unknown_stage_count: usize,
    pub(in crate::commands::real_full) uses_cuda_coordinator_kernels: bool,
    pub(in crate::commands::real_full) coordinator_graph_slots: usize,
    pub(in crate::commands::real_full) coordinator_graph_captured_graphs: usize,
    pub(in crate::commands::real_full) coordinator_graph_captures: usize,
    pub(in crate::commands::real_full) coordinator_graph_launches: usize,
    pub(in crate::commands::real_full) uses_graph_captured_coordinator_kernels: bool,
    pub(in crate::commands::real_full) stages_with_numeric_checksums: usize,
    pub(in crate::commands::real_full) total_numeric_checksum_fields: usize,
    pub(in crate::commands::real_full) numeric_checksum_fields_per_stage: usize,
    pub(in crate::commands::real_full) stages_with_tensor_artifacts: usize,
    pub(in crate::commands::real_full) total_tensor_artifacts: usize,
    pub(in crate::commands::real_full) attention_tensor_artifacts_per_stage: usize,
    pub(in crate::commands::real_full) dense_mlp_tensor_artifacts_per_stage: usize,
    pub(in crate::commands::real_full) sparse_mlp_tensor_artifacts_per_stage: usize,
    pub(in crate::commands::real_full) final_residual_checksum: Option<f64>,
    pub(in crate::commands::real_full) covers_all_layers: bool,
    pub(in crate::commands::real_full) covers_all_dense_layers: bool,
    pub(in crate::commands::real_full) covers_all_sparse_layers: bool,
    pub(in crate::commands::real_full) covers_full_top_k: bool,
    pub(in crate::commands::real_full) covers_full_output_rows: bool,
    pub(in crate::commands::real_full) stage_order_verified: bool,
    pub(in crate::commands::real_full) full_residual_stream_complete: bool,
    pub(in crate::commands::real_full) uses_full_model_residual: bool,
    pub(in crate::commands::real_full) bounded_attention_oracle:
        RealFullBoundedAttentionOracleStepperEvidence,
    pub(in crate::commands::real_full) completion_gates: RealFullResidualCompletionGates,
    pub(in crate::commands::real_full) full_residual_stream_blocker: Option<&'static str>,
}

#[derive(Debug, Clone, Serialize)]
pub(in crate::commands::real_full) struct RealFullBoundedAttentionOracleStepperEvidence {
    pub(in crate::commands::real_full) status: String,
    pub(in crate::commands::real_full) source: String,
    pub(in crate::commands::real_full) stepper_stage: String,
    pub(in crate::commands::real_full) fixture_count: usize,
    pub(in crate::commands::real_full) main_mla_fixture_count: usize,
    pub(in crate::commands::real_full) dsa_indexer_fixture_count: usize,
    pub(in crate::commands::real_full) bounded_mlp_fixture_count: usize,
    pub(in crate::commands::real_full) bounded_sparse_mlp_fixture_count: usize,
    pub(in crate::commands::real_full) bounded_terminal_fixture_count: usize,
    pub(in crate::commands::real_full) covers_real_checkpoint: bool,
    pub(in crate::commands::real_full) validates_rope_modes: bool,
    pub(in crate::commands::real_full) validates_dsa_candidate_selection: bool,
    pub(in crate::commands::real_full) validates_rmsnorm: bool,
    pub(in crate::commands::real_full) validates_gated_mlp: bool,
    pub(in crate::commands::real_full) validates_router_topk: bool,
    pub(in crate::commands::real_full) validates_sparse_routed_mlp: bool,
    pub(in crate::commands::real_full) validates_shared_mlp: bool,
    pub(in crate::commands::real_full) validates_embedding_lookup: bool,
    pub(in crate::commands::real_full) validates_lm_head_argmax: bool,
    pub(in crate::commands::real_full) main_mla_output_checksum: Option<f64>,
    pub(in crate::commands::real_full) dsa_output_checksum: Option<f64>,
    pub(in crate::commands::real_full) mlp_output_checksum: Option<f64>,
    pub(in crate::commands::real_full) residual_output_checksum: Option<f64>,
    pub(in crate::commands::real_full) sparse_mlp_output_checksum: Option<f64>,
    pub(in crate::commands::real_full) sparse_residual_output_checksum: Option<f64>,
    pub(in crate::commands::real_full) lm_head_logits_checksum: Option<f64>,
    pub(in crate::commands::real_full) lm_head_sampled_token_id: Option<usize>,
    pub(in crate::commands::real_full) dsa_selected_indices: Vec<usize>,
    pub(in crate::commands::real_full) passed: bool,
    pub(in crate::commands::real_full) remaining_gap: Option<String>,
    pub(in crate::commands::real_full) skipped_reason: Option<String>,
}

impl Default for RealFullBoundedAttentionOracleStepperEvidence {
    fn default() -> Self {
        Self {
            status: "not-run".to_owned(),
            source: "retired-stepper-validation-artifacts".to_owned(),
            stepper_stage: "retired".to_owned(),
            fixture_count: 0,
            main_mla_fixture_count: 0,
            dsa_indexer_fixture_count: 0,
            bounded_mlp_fixture_count: 0,
            bounded_sparse_mlp_fixture_count: 0,
            bounded_terminal_fixture_count: 0,
            covers_real_checkpoint: false,
            validates_rope_modes: false,
            validates_dsa_candidate_selection: false,
            validates_rmsnorm: false,
            validates_gated_mlp: false,
            validates_router_topk: false,
            validates_sparse_routed_mlp: false,
            validates_shared_mlp: false,
            validates_embedding_lookup: false,
            validates_lm_head_argmax: false,
            main_mla_output_checksum: None,
            dsa_output_checksum: None,
            mlp_output_checksum: None,
            residual_output_checksum: None,
            sparse_mlp_output_checksum: None,
            sparse_residual_output_checksum: None,
            lm_head_logits_checksum: None,
            lm_head_sampled_token_id: None,
            dsa_selected_indices: Vec::new(),
            passed: false,
            remaining_gap: None,
            skipped_reason: Some("bounded attention oracle fixture was not evaluated".to_owned()),
        }
    }
}

#[derive(Debug, Clone, Serialize)]
pub(in crate::commands::real_full) struct RealFullResidualCompletionGates {
    pub(in crate::commands::real_full) numeric_layer_order_complete: bool,
    pub(in crate::commands::real_full) attention_steps_complete: bool,
    pub(in crate::commands::real_full) residual_adds_complete: bool,
    pub(in crate::commands::real_full) covers_full_output_rows: bool,
    pub(in crate::commands::real_full) uses_embedding_residual_input: bool,
    pub(in crate::commands::real_full) uses_live_scheduler_rows: bool,
    pub(in crate::commands::real_full) uses_cuda_coordinator_kernels: bool,
    pub(in crate::commands::real_full) uses_graph_captured_coordinator_kernels: bool,
    pub(in crate::commands::real_full) uses_full_context_mla_dsa_attention: bool,
    pub(in crate::commands::real_full) uses_live_expert_daemon_moe: bool,
    pub(in crate::commands::real_full) uses_real_lm_head_sampling_residual: bool,
    pub(in crate::commands::real_full) uses_full_model_residual: bool,
    pub(in crate::commands::real_full) ready_for_full_residual_stream: bool,
    pub(in crate::commands::real_full) missing_gate_count: usize,
    pub(in crate::commands::real_full) missing_gate_names: Vec<&'static str>,
}

#[derive(Debug, Serialize)]
pub(in crate::commands::real_full) struct RealFullLayerOrderedResidualExecutionStep {
    pub(in crate::commands::real_full) layer_id: usize,
    pub(in crate::commands::real_full) stage: &'static str,
    pub(in crate::commands::real_full) stage_source: &'static str,
    pub(in crate::commands::real_full) stage_status: &'static str,
    pub(in crate::commands::real_full) executed: bool,
    pub(in crate::commands::real_full) residual_adds: usize,
    pub(in crate::commands::real_full) output_rows: usize,
    pub(in crate::commands::real_full) routes_executed: usize,
    pub(in crate::commands::real_full) selected_routes: Vec<RealFullSparseMoeRoute>,
    pub(in crate::commands::real_full) expert_host_batch_set:
        Option<RealFullSparseMoeHostBatchSetEvidence>,
    pub(in crate::commands::real_full) includes_shared_expert: bool,
    pub(in crate::commands::real_full) tensor_artifacts:
        Vec<RealFullResidualExecutionTensorArtifact>,
    pub(in crate::commands::real_full) residual_before_checksum: Option<f64>,
    pub(in crate::commands::real_full) residual_delta_checksum: Option<f64>,
    pub(in crate::commands::real_full) residual_after_checksum: Option<f64>,
    pub(in crate::commands::real_full) missing_reason: Option<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Serialize)]
pub(in crate::commands::real_full) struct RealFullSparseMoeRoute {
    pub(in crate::commands::real_full) rank: usize,
    pub(in crate::commands::real_full) expert_id: usize,
    pub(in crate::commands::real_full) owner: String,
    pub(in crate::commands::real_full) score: f32,
    pub(in crate::commands::real_full) corrected_score: f32,
    pub(in crate::commands::real_full) normalized_weight: f32,
}

#[derive(Debug, Clone, PartialEq, Serialize)]
pub(in crate::commands::real_full) struct RealFullSparseMoeHostBatchSetEvidence {
    pub(in crate::commands::real_full) status: &'static str,
    pub(in crate::commands::real_full) source: &'static str,
    pub(in crate::commands::real_full) layer_id: usize,
    pub(in crate::commands::real_full) global_rows: usize,
    pub(in crate::commands::real_full) host_batches: usize,
    pub(in crate::commands::real_full) host_rows: usize,
    pub(in crate::commands::real_full) routes: usize,
    pub(in crate::commands::real_full) hidden_dim: usize,
    pub(in crate::commands::real_full) hidden_bytes_per_row: usize,
    pub(in crate::commands::real_full) hidden_dtype: DType,
    pub(in crate::commands::real_full) graph_bucket_rows: usize,
    pub(in crate::commands::real_full) touched_hosts: Vec<String>,
    pub(in crate::commands::real_full) per_host_route_counts: Vec<usize>,
    pub(in crate::commands::real_full) reconstruction_global_rows: usize,
    pub(in crate::commands::real_full) reconstruction_host_maps: usize,
    pub(in crate::commands::real_full) protocol_v2_request_frames: usize,
    pub(in crate::commands::real_full) protocol_v2_request_rows: usize,
    pub(in crate::commands::real_full) protocol_v2_request_routes: usize,
    pub(in crate::commands::real_full) protocol_v2_hidden_payload_bytes: usize,
    pub(in crate::commands::real_full) protocol_v2_request_wire_bytes: usize,
    pub(in crate::commands::real_full) protocol_v2_views_parse: bool,
    pub(in crate::commands::real_full) protocol_v2_uses_compact_hidden_payloads: bool,
    pub(in crate::commands::real_full) protocol_v2_row_gather_backend: &'static str,
    pub(in crate::commands::real_full) protocol_v2_synthetic_executor: &'static str,
    pub(in crate::commands::real_full) protocol_v2_synthetic_response_frames: usize,
    pub(in crate::commands::real_full) protocol_v2_synthetic_response_rows: usize,
    pub(in crate::commands::real_full) protocol_v2_synthetic_response_wire_bytes: usize,
    pub(in crate::commands::real_full) protocol_v2_row_scatter_backend: &'static str,
    pub(in crate::commands::real_full) protocol_v2_accumulated_output_values: usize,
    pub(in crate::commands::real_full) protocol_v2_accumulated_contribution_counts: Vec<usize>,
    pub(in crate::commands::real_full) protocol_v2_accumulated_output_checksum: Option<f64>,
    pub(in crate::commands::real_full) protocol_v2_synthetic_outputs_finite: bool,
    pub(in crate::commands::real_full) protocol_v2_executes_route_dependent_synthetic: bool,
    pub(in crate::commands::real_full) uses_expert_input_hidden_payload: bool,
    pub(in crate::commands::real_full) uses_selected_routes: bool,
    pub(in crate::commands::real_full) uses_route_owners: bool,
    pub(in crate::commands::real_full) closes_live_expert_daemon_moe_gate: bool,
    pub(in crate::commands::real_full) skipped_reason: Option<String>,
}

#[derive(Debug, Serialize)]
pub(in crate::commands::real_full) struct RealFullResidualExecutionTensorArtifact {
    pub(in crate::commands::real_full) name: String,
    pub(in crate::commands::real_full) dtype: DType,
    pub(in crate::commands::real_full) role: TensorRole,
    pub(in crate::commands::real_full) shape: Vec<usize>,
    pub(in crate::commands::real_full) rank: usize,
    pub(in crate::commands::real_full) byte_length: u64,
    pub(in crate::commands::real_full) is_quantization_metadata: bool,
    pub(in crate::commands::real_full) rows_loaded: Option<usize>,
    pub(in crate::commands::real_full) full_tensor_loaded: bool,
    pub(in crate::commands::real_full) source: &'static str,
}
