use serde::Serialize;

#[derive(Debug, Serialize)]
pub(in crate::commands::real_full) struct RealFullSamplingDryRun {
    pub(in crate::commands::real_full) status: &'static str,
    pub(in crate::commands::real_full) scope: &'static str,
    pub(in crate::commands::real_full) lm_head_tensor: String,
    pub(in crate::commands::real_full) hidden_dim: usize,
    pub(in crate::commands::real_full) vocab_size: usize,
    pub(in crate::commands::real_full) sampled_rows: usize,
    pub(in crate::commands::real_full) hidden_dtype: &'static str,
    pub(in crate::commands::real_full) output_logit_dtype: &'static str,
    pub(in crate::commands::real_full) lm_head_bytes: u64,
    pub(in crate::commands::real_full) hidden_bytes_per_row: usize,
    pub(in crate::commands::real_full) chunk_rows: usize,
    pub(in crate::commands::real_full) chunk_count: usize,
    pub(in crate::commands::real_full) final_chunk_rows: usize,
    pub(in crate::commands::real_full) max_chunk_bytes: usize,
    pub(in crate::commands::real_full) logical_lm_head_read_bytes: u64,
    pub(in crate::commands::real_full) logical_hidden_read_bytes: usize,
    pub(in crate::commands::real_full) logical_logit_bytes: usize,
    pub(in crate::commands::real_full) dot_products: usize,
    pub(in crate::commands::real_full) multiply_accumulate_ops: u64,
    pub(in crate::commands::real_full) greedy_reduce_chunks: usize,
    pub(in crate::commands::real_full) real_lm_head_default_chunk_probe:
        RealFullSamplingLmHeadChunkProbe,
    pub(in crate::commands::real_full) real_lm_head_full_vocab_probe:
        RealFullSamplingRealLmHeadProbe,
    pub(in crate::commands::real_full) covers_full_vocabulary: bool,
    pub(in crate::commands::real_full) requires_numeric_logits: bool,
}

#[derive(Debug, Serialize)]
pub(in crate::commands::real_full) struct RealFullSamplingLmHeadChunkProbe {
    pub(in crate::commands::real_full) status: &'static str,
    pub(in crate::commands::real_full) scope: &'static str,
    pub(in crate::commands::real_full) hidden_source: &'static str,
    pub(in crate::commands::real_full) uses_real_lm_head: bool,
    pub(in crate::commands::real_full) uses_full_model_residual: bool,
    pub(in crate::commands::real_full) uses_real_dense_prefix: bool,
    pub(in crate::commands::real_full) hidden_dim: usize,
    pub(in crate::commands::real_full) vocab_size: usize,
    pub(in crate::commands::real_full) start_token_id: usize,
    pub(in crate::commands::real_full) chunk_rows: usize,
    pub(in crate::commands::real_full) rows_scored: usize,
    pub(in crate::commands::real_full) chunks_scored: usize,
    pub(in crate::commands::real_full) lm_head_bytes_read: u64,
    pub(in crate::commands::real_full) hidden_bytes: usize,
    pub(in crate::commands::real_full) logits_evaluated: usize,
    pub(in crate::commands::real_full) multiply_accumulate_ops: u64,
    pub(in crate::commands::real_full) logits_kernel_backend: Option<&'static str>,
    pub(in crate::commands::real_full) argmax_kernel_backend: Option<&'static str>,
    pub(in crate::commands::real_full) sampler_kernel_backend: Option<&'static str>,
    pub(in crate::commands::real_full) top_token_id: Option<usize>,
    pub(in crate::commands::real_full) top_logit: Option<f32>,
    pub(in crate::commands::real_full) sampled_token_id: Option<usize>,
    pub(in crate::commands::real_full) sampled_score: Option<f32>,
    pub(in crate::commands::real_full) sample_random_uniform: Option<f32>,
    pub(in crate::commands::real_full) sample_temperature: Option<f32>,
    pub(in crate::commands::real_full) sample_top_k: Option<usize>,
    pub(in crate::commands::real_full) sample_top_p: Option<f32>,
    pub(in crate::commands::real_full) residual_source_dense_layers: usize,
    pub(in crate::commands::real_full) residual_source_dense_residual_adds: usize,
    pub(in crate::commands::real_full) residual_source_dense_weight_bytes_read: u64,
    pub(in crate::commands::real_full) residual_source_covers_all_dense_layers: bool,
    pub(in crate::commands::real_full) residual_after_checksum: Option<f64>,
    pub(in crate::commands::real_full) passed: bool,
    pub(in crate::commands::real_full) error: Option<String>,
}

#[derive(Debug, Serialize)]
pub(in crate::commands::real_full) struct RealFullSamplingRealLmHeadProbe {
    pub(in crate::commands::real_full) status: &'static str,
    pub(in crate::commands::real_full) scope: &'static str,
    pub(in crate::commands::real_full) opt_in_env: &'static str,
    pub(in crate::commands::real_full) hidden_source: &'static str,
    pub(in crate::commands::real_full) uses_real_lm_head: bool,
    pub(in crate::commands::real_full) uses_full_model_residual: bool,
    pub(in crate::commands::real_full) hidden_dim: usize,
    pub(in crate::commands::real_full) vocab_size: usize,
    pub(in crate::commands::real_full) chunk_rows: usize,
    pub(in crate::commands::real_full) chunk_count: usize,
    pub(in crate::commands::real_full) final_chunk_rows: usize,
    pub(in crate::commands::real_full) chunks_scored: usize,
    pub(in crate::commands::real_full) lm_head_bytes_read: u64,
    pub(in crate::commands::real_full) hidden_bytes: usize,
    pub(in crate::commands::real_full) logits_evaluated: usize,
    pub(in crate::commands::real_full) multiply_accumulate_ops: u64,
    pub(in crate::commands::real_full) logits_kernel_backend: Option<&'static str>,
    pub(in crate::commands::real_full) argmax_kernel_backend: Option<&'static str>,
    pub(in crate::commands::real_full) sampler_kernel_backend: Option<&'static str>,
    pub(in crate::commands::real_full) top_token_id: Option<usize>,
    pub(in crate::commands::real_full) top_logit: Option<f32>,
    pub(in crate::commands::real_full) sampled_token_id: Option<usize>,
    pub(in crate::commands::real_full) sampled_score: Option<f32>,
    pub(in crate::commands::real_full) sample_random_uniform: Option<f32>,
    pub(in crate::commands::real_full) sample_temperature: Option<f32>,
    pub(in crate::commands::real_full) sample_top_k: Option<usize>,
    pub(in crate::commands::real_full) sample_top_p: Option<f32>,
    pub(in crate::commands::real_full) uses_real_attention_prefix: bool,
    pub(in crate::commands::real_full) uses_real_nvfp4_residual_prefix: bool,
    pub(in crate::commands::real_full) uses_real_nvfp4_residual_chain: bool,
    pub(in crate::commands::real_full) uses_real_sparse_mlp_shared_chain: bool,
    pub(in crate::commands::real_full) uses_real_dense_prefix: bool,
    pub(in crate::commands::real_full) residual_source_layer_id: Option<usize>,
    pub(in crate::commands::real_full) residual_source_attention_rows: usize,
    pub(in crate::commands::real_full) residual_source_attention_residual_adds: usize,
    pub(in crate::commands::real_full) residual_source_includes_causal_softmax: bool,
    pub(in crate::commands::real_full) residual_source_includes_mla_softmax: bool,
    pub(in crate::commands::real_full) residual_source_dense_layers: usize,
    pub(in crate::commands::real_full) residual_source_dense_residual_adds: usize,
    pub(in crate::commands::real_full) residual_source_dense_norm_bytes_read: u64,
    pub(in crate::commands::real_full) residual_source_dense_weight_bytes_read: u64,
    pub(in crate::commands::real_full) residual_source_covers_all_dense_layers: bool,
    pub(in crate::commands::real_full) residual_source_sparse_layers: usize,
    pub(in crate::commands::real_full) residual_source_top_k: usize,
    pub(in crate::commands::real_full) residual_source_route_count: usize,
    pub(in crate::commands::real_full) residual_source_output_rows: usize,
    pub(in crate::commands::real_full) residual_source_residual_adds: usize,
    pub(in crate::commands::real_full) residual_source_total_residual_adds: usize,
    pub(in crate::commands::real_full) residual_source_router_weight_bytes_read: u64,
    pub(in crate::commands::real_full) residual_source_router_bias_bytes_read: u64,
    pub(in crate::commands::real_full) residual_source_weight_bytes_read: u64,
    pub(in crate::commands::real_full) residual_source_quant_metadata_bytes_read: u64,
    pub(in crate::commands::real_full) residual_source_shared_expert_layers: usize,
    pub(in crate::commands::real_full) residual_source_shared_weight_bytes_read: u64,
    pub(in crate::commands::real_full) residual_source_covers_all_sparse_layers: bool,
    pub(in crate::commands::real_full) residual_source_covers_full_top_k: bool,
    pub(in crate::commands::real_full) residual_prefix_values: usize,
    pub(in crate::commands::real_full) residual_before_checksum: Option<f64>,
    pub(in crate::commands::real_full) residual_delta_checksum: Option<f64>,
    pub(in crate::commands::real_full) residual_after_checksum: Option<f64>,
    pub(in crate::commands::real_full) passed: bool,
    pub(in crate::commands::real_full) skipped_reason: Option<String>,
}
