use serde::Serialize;

#[derive(Debug, Serialize)]
pub(in crate::commands::real_full) struct RealFullSchedulerDryRun {
    pub(in crate::commands::real_full) status: &'static str,
    pub(in crate::commands::real_full) scope: &'static str,
    pub(in crate::commands::real_full) placement_version: String,
    pub(in crate::commands::real_full) request_id: &'static str,
    pub(in crate::commands::real_full) sequence_id: &'static str,
    pub(in crate::commands::real_full) kv_reservation_id: u64,
    pub(in crate::commands::real_full) total_layerwaves: usize,
    pub(in crate::commands::real_full) decode_layerwaves: usize,
    pub(in crate::commands::real_full) prefill_layerwaves: usize,
    pub(in crate::commands::real_full) mtp_verify_layerwaves: usize,
    pub(in crate::commands::real_full) dense_coordinator_layers: usize,
    pub(in crate::commands::real_full) sparse_expert_batches: usize,
    pub(in crate::commands::real_full) graph_bucket_rows: usize,
    pub(in crate::commands::real_full) rows_per_sparse_expert_batch: usize,
    pub(in crate::commands::real_full) routes_per_sparse_expert_batch: usize,
    pub(in crate::commands::real_full) decode_prefix_read_layers: usize,
    pub(in crate::commands::real_full) decode_kv_write_layers: usize,
    pub(in crate::commands::real_full) prefill_prefix_read_layers: usize,
    pub(in crate::commands::real_full) prefill_kv_write_layers: usize,
    pub(in crate::commands::real_full) mtp_prefix_read_layers: usize,
    pub(in crate::commands::real_full) mtp_tentative_write_records: usize,
    pub(in crate::commands::real_full) protocol_v2_batch_probe:
        RealFullSchedulerProtocolV2BatchProbe,
    pub(in crate::commands::real_full) layer_dry_runs: Vec<RealFullLayerSchedulerDryRun>,
}

#[derive(Debug, Serialize)]
pub(in crate::commands::real_full) struct RealFullLayerSchedulerDryRun {
    pub(in crate::commands::real_full) layer_id: usize,
    pub(in crate::commands::real_full) layer_kind: &'static str,
    pub(in crate::commands::real_full) decode: RealFullWaveDryRun,
    pub(in crate::commands::real_full) prefill: RealFullWaveDryRun,
    pub(in crate::commands::real_full) mtp_verify: RealFullWaveDryRun,
    pub(in crate::commands::real_full) expert_batch: Option<RealFullExpertBatchDryRun>,
}

#[derive(Debug, Clone, Copy, Serialize)]
pub(in crate::commands::real_full) struct RealFullWaveDryRun {
    pub(in crate::commands::real_full) mode: &'static str,
    pub(in crate::commands::real_full) rows: usize,
    pub(in crate::commands::real_full) graph_bucket_rows: usize,
    pub(in crate::commands::real_full) payload_bytes: usize,
    pub(in crate::commands::real_full) kv_reads: usize,
    pub(in crate::commands::real_full) kv_writes: usize,
    pub(in crate::commands::real_full) tentative_kv_writes: usize,
}

#[derive(Debug, Serialize)]
pub(in crate::commands::real_full) struct RealFullExpertBatchDryRun {
    pub(in crate::commands::real_full) rows: usize,
    pub(in crate::commands::real_full) routes: usize,
    pub(in crate::commands::real_full) graph_bucket_rows: usize,
    pub(in crate::commands::real_full) source_modes: Vec<&'static str>,
    pub(in crate::commands::real_full) hidden_dim: usize,
    pub(in crate::commands::real_full) hidden_bytes_per_row: usize,
}

#[derive(Debug, Serialize)]
pub(in crate::commands::real_full) struct RealFullSchedulerProtocolV2BatchProbe {
    pub(in crate::commands::real_full) status: &'static str,
    pub(in crate::commands::real_full) scope: &'static str,
    pub(in crate::commands::real_full) layer_id: usize,
    pub(in crate::commands::real_full) rows: usize,
    pub(in crate::commands::real_full) routes: usize,
    pub(in crate::commands::real_full) source_modes: Vec<&'static str>,
    pub(in crate::commands::real_full) hidden_dim: usize,
    pub(in crate::commands::real_full) hidden_bytes_per_row: usize,
    pub(in crate::commands::real_full) hidden_payload_bytes: usize,
    pub(in crate::commands::real_full) request_wire_bytes: usize,
    pub(in crate::commands::real_full) response_wire_bytes: usize,
    pub(in crate::commands::real_full) request_logical_payload_bytes: usize,
    pub(in crate::commands::real_full) response_logical_payload_bytes: usize,
    pub(in crate::commands::real_full) request_frame_buffer_capacity_bytes: usize,
    pub(in crate::commands::real_full) response_frame_buffer_capacity_bytes: usize,
    pub(in crate::commands::real_full) request_frame_buffer_stable: bool,
    pub(in crate::commands::real_full) response_frame_buffer_stable: bool,
    pub(in crate::commands::real_full) decoded_request_matches: bool,
    pub(in crate::commands::real_full) decoded_response_matches: bool,
    pub(in crate::commands::real_full) reconstructed_response_rows: usize,
    pub(in crate::commands::real_full) reconstructed_response_payload_bytes: usize,
    pub(in crate::commands::real_full) reconstructed_response_row_order_matches: bool,
    pub(in crate::commands::real_full) reconstructed_response_payload_matches: bool,
    pub(in crate::commands::real_full) host_batches: usize,
    pub(in crate::commands::real_full) host_batch_rows: usize,
    pub(in crate::commands::real_full) host_batch_routes: usize,
    pub(in crate::commands::real_full) host_batch_expert_tiles: usize,
    pub(in crate::commands::real_full) host_batch_routes_match_global: bool,
    pub(in crate::commands::real_full) host_batch_graph_counts_valid: bool,
    pub(in crate::commands::real_full) host_request_frames: usize,
    pub(in crate::commands::real_full) host_request_rows: usize,
    pub(in crate::commands::real_full) host_request_routes: usize,
    pub(in crate::commands::real_full) host_request_payload_bytes: usize,
    pub(in crate::commands::real_full) host_request_wire_bytes: usize,
    pub(in crate::commands::real_full) host_response_frames: usize,
    pub(in crate::commands::real_full) host_response_rows: usize,
    pub(in crate::commands::real_full) host_response_payload_bytes: usize,
    pub(in crate::commands::real_full) host_response_wire_bytes: usize,
    pub(in crate::commands::real_full) host_wire_envelopes_valid: bool,
    pub(in crate::commands::real_full) passed: bool,
}

#[derive(Debug, Serialize)]
pub(in crate::commands::real_full) struct RealFullSchedulerExecutionDryRun {
    pub(in crate::commands::real_full) status: &'static str,
    pub(in crate::commands::real_full) scope: &'static str,
    pub(in crate::commands::real_full) request_prefill_tokens: usize,
    pub(in crate::commands::real_full) request_prefill_chunks: usize,
    pub(in crate::commands::real_full) request_decode_rows: usize,
    pub(in crate::commands::real_full) request_mtp_verify_rows: usize,
    pub(in crate::commands::real_full) request_mtp_accepted_rows: usize,
    pub(in crate::commands::real_full) request_coordinator_graph_slots: usize,
    pub(in crate::commands::real_full) request_coordinator_graph_captured_graphs: usize,
    pub(in crate::commands::real_full) request_coordinator_graph_captures: usize,
    pub(in crate::commands::real_full) request_coordinator_graph_launches: usize,
    pub(in crate::commands::real_full) iterations: usize,
    pub(in crate::commands::real_full) candidate_layerwaves: usize,
    pub(in crate::commands::real_full) selected_layerwaves: usize,
    pub(in crate::commands::real_full) deferred_layerwaves: usize,
    pub(in crate::commands::real_full) selected_decode_rows: usize,
    pub(in crate::commands::real_full) selected_prefill_rows: usize,
    pub(in crate::commands::real_full) selected_mtp_rows: usize,
    pub(in crate::commands::real_full) sparse_expert_batches: usize,
    pub(in crate::commands::real_full) sparse_expert_batch_rows: usize,
    pub(in crate::commands::real_full) sparse_expert_batch_routes: usize,
    pub(in crate::commands::real_full) sparse_expert_prefill_rows: usize,
    pub(in crate::commands::real_full) sparse_expert_decode_rows: usize,
    pub(in crate::commands::real_full) sparse_expert_mtp_verify_rows: usize,
    pub(in crate::commands::real_full) sparse_expert_prefill_routes: usize,
    pub(in crate::commands::real_full) sparse_expert_decode_routes: usize,
    pub(in crate::commands::real_full) sparse_expert_mtp_verify_routes: usize,
    pub(in crate::commands::real_full) sparse_expert_host_batch_sets: usize,
    pub(in crate::commands::real_full) sparse_expert_host_batches: usize,
    pub(in crate::commands::real_full) sparse_expert_host_batch_rows: usize,
    pub(in crate::commands::real_full) sparse_expert_host_batch_routes: usize,
    pub(in crate::commands::real_full) sparse_expert_host_batch_expert_tiles: usize,
    pub(in crate::commands::real_full) sparse_expert_host_batch_routes_match_global: bool,
    pub(in crate::commands::real_full) sparse_expert_host_batch_graph_counts_valid: bool,
    pub(in crate::commands::real_full) sparse_expert_host_request_frames: usize,
    pub(in crate::commands::real_full) sparse_expert_host_request_rows: usize,
    pub(in crate::commands::real_full) sparse_expert_host_request_routes: usize,
    pub(in crate::commands::real_full) sparse_expert_host_request_payload_bytes: usize,
    pub(in crate::commands::real_full) sparse_expert_host_request_wire_bytes: usize,
    pub(in crate::commands::real_full) sparse_expert_host_response_frames: usize,
    pub(in crate::commands::real_full) sparse_expert_host_response_rows: usize,
    pub(in crate::commands::real_full) sparse_expert_host_response_payload_bytes: usize,
    pub(in crate::commands::real_full) sparse_expert_host_response_wire_bytes: usize,
    pub(in crate::commands::real_full) sparse_expert_host_wire_envelopes_valid: bool,
    pub(in crate::commands::real_full) kv_read_blocks: usize,
    pub(in crate::commands::real_full) committed_kv_writes: usize,
    pub(in crate::commands::real_full) tentative_kv_writes: usize,
    pub(in crate::commands::real_full) projected_device_kv_writes: usize,
    pub(in crate::commands::real_full) projected_device_kv_write_bytes: usize,
    pub(in crate::commands::real_full) synthetic_kv_payload_writes: usize,
    pub(in crate::commands::real_full) committed_mtp_writes: usize,
    pub(in crate::commands::real_full) discarded_mtp_writes: usize,
    pub(in crate::commands::real_full) backed_kv_writes: usize,
    pub(in crate::commands::real_full) backed_bytes_after_discard: usize,
    pub(in crate::commands::real_full) kv_reservation_bytes: usize,
    pub(in crate::commands::real_full) byte_backed_scheduler_trace: bool,
    pub(in crate::commands::real_full) device_kv_status: &'static str,
    pub(in crate::commands::real_full) device_kv_writes: usize,
    pub(in crate::commands::real_full) device_kv_reads: usize,
    pub(in crate::commands::real_full) device_kv_bytes: usize,
    pub(in crate::commands::real_full) uses_device_kv_cache: bool,
    pub(in crate::commands::real_full) device_attention_resident_uploads: usize,
    pub(in crate::commands::real_full) device_attention_resident_buffer_uses: usize,
    pub(in crate::commands::real_full) device_attention_resident_query_shapes: usize,
    pub(in crate::commands::real_full) device_attention_status: &'static str,
    pub(in crate::commands::real_full) device_attention_launches: usize,
    pub(in crate::commands::real_full) device_attention_rows: usize,
    pub(in crate::commands::real_full) device_attention_query_rows: usize,
    pub(in crate::commands::real_full) device_attention_kv_descriptors: usize,
    pub(in crate::commands::real_full) device_attention_output_bytes: usize,
    pub(in crate::commands::real_full) device_attention_output_values: usize,
    pub(in crate::commands::real_full) device_attention_output_finite_values: usize,
    pub(in crate::commands::real_full) device_attention_output_nonzero_values: usize,
    pub(in crate::commands::real_full) device_attention_output_checksum: f64,
    pub(in crate::commands::real_full) device_attention_hidden_projection_launches: usize,
    pub(in crate::commands::real_full) uses_device_kv_attention: bool,
    pub(in crate::commands::real_full) full_context_device_attention_complete: bool,
    pub(in crate::commands::real_full) numeric_progression_self_test:
        RealFullSchedulerNumericProgressionSelfTest,
    pub(in crate::commands::real_full) terminal_lm_head_sample:
        RealFullSchedulerTerminalLmHeadSample,
    pub(in crate::commands::real_full) layer_order_verified: bool,
}

#[derive(Debug, Serialize)]
pub(in crate::commands::real_full) struct RealFullSchedulerTerminalLmHeadSample {
    pub(in crate::commands::real_full) status: &'static str,
    pub(in crate::commands::real_full) scope: &'static str,
    pub(in crate::commands::real_full) uses_final_decode_device_hidden: bool,
    pub(in crate::commands::real_full) covers_full_vocabulary: bool,
    pub(in crate::commands::real_full) hidden_dim: usize,
    pub(in crate::commands::real_full) vocab_size: usize,
    pub(in crate::commands::real_full) logits_evaluated: usize,
    pub(in crate::commands::real_full) top_token_id: Option<usize>,
    pub(in crate::commands::real_full) sampled_token_id: Option<usize>,
    pub(in crate::commands::real_full) sample_top_k: Option<usize>,
    pub(in crate::commands::real_full) sample_top_p: Option<f32>,
    pub(in crate::commands::real_full) argmax_kernel_backend: Option<&'static str>,
    pub(in crate::commands::real_full) sampler_kernel_backend: Option<&'static str>,
    pub(in crate::commands::real_full) passed: bool,
    pub(in crate::commands::real_full) blocker: Option<String>,
}

#[derive(Debug, Serialize)]
pub(in crate::commands::real_full) struct RealFullSchedulerNumericProgressionSelfTest {
    pub(in crate::commands::real_full) status: &'static str,
    pub(in crate::commands::real_full) scope: &'static str,
    pub(in crate::commands::real_full) layers: usize,
    pub(in crate::commands::real_full) source_modes: [&'static str; 3],
    pub(in crate::commands::real_full) unique_source_rows: usize,
    pub(in crate::commands::real_full) hidden_dim: usize,
    pub(in crate::commands::real_full) residual_dtype: &'static str,
    pub(in crate::commands::real_full) selected_prefill_rows: usize,
    pub(in crate::commands::real_full) selected_decode_rows: usize,
    pub(in crate::commands::real_full) selected_mtp_rows: usize,
    pub(in crate::commands::real_full) mtp_accepted_rows_per_layer: usize,
    pub(in crate::commands::real_full) mtp_rejected_rows_per_layer: usize,
    pub(in crate::commands::real_full) source_segments: usize,
    pub(in crate::commands::real_full) attention_residual_adds: usize,
    pub(in crate::commands::real_full) mlp_residual_adds: usize,
    pub(in crate::commands::real_full) attention_residual_add_backend: &'static str,
    pub(in crate::commands::real_full) mlp_residual_add_backend: &'static str,
    pub(in crate::commands::real_full) attention_value_updates: usize,
    pub(in crate::commands::real_full) mlp_value_updates: usize,
    pub(in crate::commands::real_full) device_attention_output_delta_status: &'static str,
    pub(in crate::commands::real_full) attention_device_output_delta_rows: usize,
    pub(in crate::commands::real_full) attention_device_output_delta_values: usize,
    pub(in crate::commands::real_full) attention_device_output_delta_checksum: f64,
    pub(in crate::commands::real_full) attention_device_output_delta_backend: &'static str,
    pub(in crate::commands::real_full) attention_device_output_delta_device_prefix_rows: usize,
    pub(in crate::commands::real_full) attention_device_output_delta_device_prefix_values: usize,
    pub(in crate::commands::real_full) attention_device_output_delta_device_prefix_backend:
        &'static str,
    pub(in crate::commands::real_full) uses_device_attention_output_delta: bool,
    pub(in crate::commands::real_full) device_delta_template_status: &'static str,
    pub(in crate::commands::real_full) device_delta_template_uploads: usize,
    pub(in crate::commands::real_full) device_delta_template_uses: usize,
    pub(in crate::commands::real_full) device_delta_template_resident_values: usize,
    pub(in crate::commands::real_full) device_mlp_delta_status: &'static str,
    pub(in crate::commands::real_full) device_mlp_delta_rows: usize,
    pub(in crate::commands::real_full) device_mlp_delta_values: usize,
    pub(in crate::commands::real_full) device_mlp_delta_checksum: f64,
    pub(in crate::commands::real_full) device_mlp_delta_backend: &'static str,
    pub(in crate::commands::real_full) device_mlp_weight_uploads: usize,
    pub(in crate::commands::real_full) device_mlp_weight_resident_values: usize,
    pub(in crate::commands::real_full) uses_device_mlp_delta: bool,
    pub(in crate::commands::real_full) device_real_dense_mlp_delta_status: &'static str,
    pub(in crate::commands::real_full) device_real_dense_mlp_delta_rows: usize,
    pub(in crate::commands::real_full) device_real_dense_mlp_delta_values: usize,
    pub(in crate::commands::real_full) device_real_dense_mlp_delta_checksum: f64,
    pub(in crate::commands::real_full) device_real_dense_mlp_delta_backend: &'static str,
    pub(in crate::commands::real_full) device_real_dense_mlp_norm_backend: &'static str,
    pub(in crate::commands::real_full) device_real_dense_mlp_weight_tensors: usize,
    pub(in crate::commands::real_full) device_real_dense_mlp_weight_bytes: u64,
    pub(in crate::commands::real_full) device_real_dense_mlp_layers: usize,
    pub(in crate::commands::real_full) device_real_dense_mlp_source_segments: usize,
    pub(in crate::commands::real_full) uses_device_real_dense_mlp_delta: bool,
    pub(in crate::commands::real_full) device_real_sparse_shared_mlp_delta_status: &'static str,
    pub(in crate::commands::real_full) device_real_sparse_shared_mlp_delta_rows: usize,
    pub(in crate::commands::real_full) device_real_sparse_shared_mlp_delta_values: usize,
    pub(in crate::commands::real_full) device_real_sparse_shared_mlp_delta_checksum: f64,
    pub(in crate::commands::real_full) device_real_sparse_shared_mlp_delta_backend: &'static str,
    pub(in crate::commands::real_full) device_real_sparse_shared_mlp_norm_backend: &'static str,
    pub(in crate::commands::real_full) device_real_sparse_shared_mlp_weight_tensors: usize,
    pub(in crate::commands::real_full) device_real_sparse_shared_mlp_weight_bytes: u64,
    pub(in crate::commands::real_full) device_real_sparse_shared_mlp_layers: usize,
    pub(in crate::commands::real_full) device_real_sparse_shared_mlp_source_segments: usize,
    pub(in crate::commands::real_full) uses_device_real_sparse_shared_mlp_delta: bool,
    pub(in crate::commands::real_full) device_real_sparse_routed_mlp_delta_status: &'static str,
    pub(in crate::commands::real_full) device_real_sparse_routed_mlp_delta_rows: usize,
    pub(in crate::commands::real_full) device_real_sparse_routed_mlp_delta_values: usize,
    pub(in crate::commands::real_full) device_real_sparse_routed_mlp_delta_checksum: f64,
    pub(in crate::commands::real_full) device_real_sparse_routed_mlp_delta_backend: &'static str,
    pub(in crate::commands::real_full) device_real_sparse_routed_mlp_route_backend: &'static str,
    pub(in crate::commands::real_full) device_real_sparse_routed_mlp_router_backend: &'static str,
    pub(in crate::commands::real_full) device_real_sparse_routed_mlp_routes: usize,
    pub(in crate::commands::real_full) device_real_sparse_routed_mlp_router_weight_bytes: u64,
    pub(in crate::commands::real_full) device_real_sparse_routed_mlp_router_bias_bytes: u64,
    pub(in crate::commands::real_full) device_real_sparse_routed_mlp_route_cache_cuda_entries:
        usize,
    pub(in crate::commands::real_full) device_real_sparse_routed_mlp_route_cache_cuda_uploads:
        usize,
    pub(in crate::commands::real_full) device_real_sparse_routed_mlp_route_cache_cuda_hits: usize,
    pub(in crate::commands::real_full) device_real_sparse_routed_mlp_router_cache_entries: usize,
    pub(in crate::commands::real_full) device_real_sparse_routed_mlp_router_cache_hits: usize,
    pub(in crate::commands::real_full) device_real_sparse_routed_mlp_layers: usize,
    pub(in crate::commands::real_full) device_real_sparse_routed_mlp_source_segments: usize,
    pub(in crate::commands::real_full) uses_device_real_sparse_routed_mlp_delta: bool,
    pub(in crate::commands::real_full) device_hidden_segment_status: &'static str,
    pub(in crate::commands::real_full) device_hidden_segment_residual_adds: usize,
    pub(in crate::commands::real_full) device_hidden_segment_value_updates: usize,
    pub(in crate::commands::real_full) device_hidden_segment_residual_add_backend: &'static str,
    pub(in crate::commands::real_full) device_hidden_segment_resident_segments: usize,
    pub(in crate::commands::real_full) device_hidden_segment_resident_values: usize,
    pub(in crate::commands::real_full) device_hidden_segment_final_checksum: f32,
    pub(in crate::commands::real_full) expected_device_hidden_segment_final_checksum: f32,
    pub(in crate::commands::real_full) uses_device_hidden_segment_residual_add: bool,
    pub(in crate::commands::real_full) final_visible_checksum: f32,
    pub(in crate::commands::real_full) expected_visible_checksum: f32,
    pub(in crate::commands::real_full) rejected_mtp_checksum: f32,
    pub(in crate::commands::real_full) expected_rejected_mtp_checksum: f32,
    pub(in crate::commands::real_full) passed: bool,
}
